### ISSUE TITLE
Character built in 180 Fails to load

### ISSUE THREAD

**Issue by SeanPGorman** [chummer5a/chummer5a#958] opened 2016-06-24 21:58 UTC
Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version
181:31

### Expected behaviour
Character loads fine

### Actual behaviour
Crash report sent

### Steps to reproduce the behaviour
none

### Link to affected character file
https://www.dropbox.com/s/0nzi3q34wy11cbw/Nev-yn.chum5?dl=0

**Comment by joha4270** [comment] 2016-06-25 08:25
Loads fine for  me (181.34) and no crash report has ever been submitted for 181.31.

I'm going to need the crash followup id that the crash reporter mentions  to have any chance as diagnosing this or i'll have to close this issue.

**Comment by SeanPGorman** [comment] 2016-06-25 11:02
I just recreated it in 31. 
6.01am cst
Crash followup id = 54147615-4153-4549-90c2-089908235950

**Comment by SeanPGorman** [comment] 2016-06-25 11:30
Also: right from the error log:
Info      Program.cs.Main:68 Application Chummer5a build 5.181.34.0 started at 6/25/2016 11:27:42 AM with command line arguments "C:\Chummer5\Chummer5.exe" "C:\Chummer5\Characters\Grinwald.chum5"
Error     clsXmlExtensions.cs.CheckGetField:183 Tried to read missing field "recentimagefolder" of type "System.String" in System.String.CharacterOptions
Info      clsTimekeeper.cs.Finish:67 Task "load_xml" finished in 00:00:00.0267618
First chance exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.Character.Load() in C:\projects\chummer5a\Chummer\Classes\clsCharacter.cs:line 949
Error     clsXmlExtensions.cs.CheckGetField:183 Tried to read missing field "recentimagefolder" of type "System.String" in System.String.CharacterOptions
Error     clsXmlExtensions.cs.CheckGetField:183 Tried to read missing field "iscritter" of type "System.Boolean" in System.Boolean.Character
Error     clsXmlExtensions.cs.CheckGetField:183 Tried to read missing field "possessed" of type "System.Boolean" in System.Boolean.Character
Error     clsXmlExtensions.cs.CheckGetField:183 Tried to read missing field "overridespecialattributeessloss" of type "System.Boolean" in System.Boolean.Character
Error     clsXmlExtensions.cs.CheckGetField:183 Tried to read missing field "blackmarket" of type "System.Boolean" in System.Boolean.Character
Info      clsTimekeeper.cs.Finish:67 Task "load_char_misc" finished in 00:00:00.0073610

**Comment by jrrickerson** [comment] 2016-06-28 03:28
I'm seeing what looks like a very similar issue.

Chummer 5a 5.180.46.0
OS: Windows 10 Home, 64 bit.

No crash id as the crash reporter itself appears to also be crashing.
![crash_report_failure](https://cloud.githubusercontent.com/assets/184687/16402973/c84404b6-3cbe-11e6-937c-2da4231bb521.png)


I've built 3 other characters just fine with this exact version of Chummer, but another of my players built his own character on his own, using the same version of Chummer.

Crash log and offending character sheet are attached.
[character_load_crash.zip](https://github.com/chummer5a/chummer5a/files/336216/character_load_crash.zip)

**Comment by SeanPGorman** [comment] 2016-06-30 00:56
Adding Crash followup id = 7ecd0fb6-05f1-4207-bc7a-857bc28769ef from build 181.53. 

Same character still not loading

**Comment by joha4270** [comment] 2016-06-30 09:40
Okay, this took me a while to figure out, but i know what the cause is now. Not sure when/if i get around to fixing it. 

Disable the "Essence loss only impacts Maximum MAG/RES" under "options > house rules" and "Nu-yen" loads fine(ish)

Still noted as not having any magic. This can be solved either by removing and adding adept, or by changing line 259 to True

To reiterate, the root cause is cyberadepts and reduce maximum essence not playing nice with how we calculate Base/Karma. 

The issue experienced by @jrrickerson is **not** related to this issue. I can only advice him to isolate what makes the 3rd character crash. Start by seeing if new character just saved crashes, and work toward the version that crashes. Once it crashes, note what changed and try half of it, until he findes a single thing/list of things that can provoke the crash. Once he has that, he should create a new issue.

**Comment by chummer5a** [comment] 2016-08-16 06:21
Should be resolved in current builds due to changes to essence loss code.

**Closed by chummer5a** 2016-08-16 06:21 UTC
