### ISSUE TITLE
Positiv or negative concealability modifier for weapons does not work.

### ISSUE THREAD

**Issue by McRipolo** [chummer5a/chummer5a#588] opened 2015-12-22 16:34 UTC
I think the Weapon Mods has lost their concealability modifier stats.

Excuse me if I annoy you, I think the errors haunt me;-)

**Comment by joha4270** [comment] 2015-12-22 16:36
This works for me. Try downloading the latest version [here](https://github.com/chummer5a/chummer5a/releases/latest) and see if the issue persists. Otherwise i need exact steps to reproduction (ex, press "new character", "human"...)

**Comment by McRipolo** [comment] 2015-12-22 17:14
I have tested again with this Version, and the 1 hour old nightly Version, it works not with Long Barrel, Foregrip or Chameleon Coating, only with Extended Clip in both Ratings.

**Comment by McRipolo** [comment] 2015-12-22 17:33
by the way, please add Conceal to the weapon stats on the char sheet

**Comment by McRipolo** [comment] 2015-12-22 17:53
Some testings done, the problem starts with Nightly-v1.0.534 , the other version befor works fine.
Hope that helped.

**Comment by chummer5a** [comment] 2015-12-25 16:36
Fixed in 5.179 or the next nightly build I commit.

**Closed by chummer5a** 2015-12-25 16:36 UTC
