### ISSUE TITLE
Adding gear to armor crash

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#1979] opened 2017-10-19 21:51 UTC
### Environment
Chummer Version: 5.195.46
Environment: Windows 10
Runtime:  probably .NET 4.5.1

### Expected behaviour
Chummer not to crash.

### Actual behaviour
Chummer crashes when you add any gear to any armor.
(I tested with gas mask on ballistic mask and some other stuff on another piece of armor.)

### Steps to reproduce the behaviour
Create new character. Buy armor. Add gear.

**Comment by OLStefan** [comment] 2017-10-19 21:53
Very probably a Duplicate of #1978 and should be fixed in the version 5.195.47. Please test again tomorrow if this issue in still there.

**Comment by DelnarErsike** [comment] 2017-10-20 03:27
D'oh, there was another thing there that caused a null pointer dereference. Pushed a quick fix for it to dev build.

**Closed by DelnarErsike** 2017-10-20 03:27 UTC
Labels: bug: application error, duplicate
