### ISSUE TITLE
Houserule "Free Contact Points" prevents buying more Contacts then you have points

### ISSUE THREAD

**Issue by Tom-0169** [chummer5a/chummer5a#216] opened 2015-05-20 18:23 UTC
Chummer 5.166
in House Rules check
Karma Build Free Contacts like Priority Build
Karma Build Free Knowledge Skill Points like Priority Build

create a new Char
Add a contact
take some levels in Connection & loyality
you get something like: -2 of 3 (0 Karma)

**Comment by joha4270** [comment] 2015-05-20 18:31
Just to be sure, are the - intended or a mistake? 
If it is intended, then i'm not able to reproduce on dev or 5.165

If the - is unintended, that is exactly how it supposed to work.
You have spend 2 points on contacts out of 3 free and you are paying 0 karma for that

**Comment by Tom-0169** [comment] 2015-05-20 18:33
I took a fresh install and get a negative value for Contact points

**Comment by joha4270** [comment] 2015-05-20 18:39
I can't reproduce either of those issues, neither in 5165 nor 5166

**Comment by Tom-0169** [comment] 2015-05-20 18:45
Can reproduce this on two independent Win7Pro64 machines
My own & the PC @Work

**Comment by Tom-0169** [comment] 2015-05-20 19:12
Just tried it on my Laptop...
No error reproducible.
Running Win7 Home Premium 64bit
Seems to be a system related issue

**Comment by joha4270** [comment] 2015-06-11 19:35
As this seems to be a windows specific issue and i'm unable to reproduce, i'm closing this until i receive detailed instructions on how to replicated.

**Closed by joha4270** 2015-06-11 19:35 UTC
