### ISSUE TITLE
Consistent crash-to-desktop after adding Ammo: Injection Darts

### ISSUE THREAD

**Issue by Anon5342** [chummer5a/chummer5a#4496] opened 2021-06-23 22:52 UTC
**Description:**
As title.  This also fails to create a crash report, though it provides an error message (screenshot 2 below).

**Steps to reproduce:**
1. Open up any character or a new character
2. Go to the street gear tab
3. Click "Add Gear" and select "Ammo: Injection Darts"
4. A popup box will ask you to select Weapon Category, but no selections will be available (screenshot 1 below).
5. After clicking "Ok", see error message before Chummer crashes.

**Expected behavior**
An entry for "Ammo: Injection Darts" should be added to the gear list, perhaps with a parenthetical for the type of weapon they're used with (Dart Pistol, Dart Rifle, or Blowgun).

**Screenshot 1:**
![image](https://user-images.githubusercontent.com/86385082/123177622-9dd09a00-d453-11eb-9154-7e0edd7effea.png)

**Screenshot 2:**
![image](https://user-images.githubusercontent.com/86385082/123177721-d07a9280-d453-11eb-9178-874cf5b30f93.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chummer Version 5.214.0

**Additional details:**
Issue was not fixed by a fresh reinstall.

**Comment by JoschiGrey** [comment] 2021-06-24 11:11
This should be fixed in nightly, at least I can't reproduce it and worked on that code a while back to resolve a similar issue.

**Closed** 2021-06-26 11:18 UTC
