### ISSUE TITLE
Crashes when I click the skill tab

### ISSUE THREAD

**Issue by cchopps** [chummer5a/chummer5a#941] opened 2016-06-19 01:28 UTC
Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version
5.181.19 (Nightly) [English]
Win7 64bit.

### Expected behaviour
Click on skill tab and see the skills page

### Actual behaviour
Crash! pop-up. And the skill page is blank.

### Steps to reproduce the behaviour
Create a character using Life Modules. After selecting life module I then click on the skills tab.

### Link to affected character file
[Crash Character.zip](https://github.com/chummer5a/chummer5a/files/322056/Crash.Character.zip)

**Comment by chummer5a** [comment] 2016-06-21 11:09
Can you please test with the latest nightly? If it crashes again, please provide the Crash Handler report.

**Comment by Len1991** [comment] 2016-06-23 10:26
Having the same Issue just tested it with the last nightly and it still happens, Crash Handler report is send.

**Comment by joha4270** [comment] 2016-06-23 10:27
@Len1991 the crash mentions a "crash followup id" did you make a note of that?

**Comment by joha4270** [comment] 2016-06-23 18:37
@Len1991 Found a crash report that is _probably_ yours (was in skill related code but i'm guessing)

Looking at it, i think i have fixed the issue, but i haven't been able to reproduce it. It seems to be related to font or zoom, but haven't been able to reproduce it on my system.

Would love to know if the issue is still persistent in [Nightly v5.181.31](https://github.com/chummer5a/chummer5a/tree/Nightly-v5.181.31) or later builds

**Comment by Sceptically** [comment] 2016-06-25 08:35
I was having the same issue, which is now fixed. I can actually do things with the skills tab now...

**Comment by joha4270** [comment] 2016-06-25 08:37
@Sceptically Great to hear that it is fixed for somebody. Wanting to see a few more confirmations before i declare this group of issues fixed, but i can see the light at the end of the tunnel now.

**Comment by Len1991** [comment] 2016-06-25 14:33
Fixed for me too... And i want to add u are doing an awesome job, keep going

**Comment by joha4270** [comment] 2016-06-28 16:01
We have received reports that this issue is fixed in nighties. Unless or until we get contrary reports i'm going to close this issue.

**Closed by joha4270** 2016-06-28 16:01 UTC
