### ISSUE TITLE
Skill pools not updated

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#3346] opened 2019-01-10 14:02 UTC
**Value of attribute when calculating skill pool is not updated. **

Have seen both attribute starting low (at 1) and skill pool not updating when I raise the att and attribute stating high and skill pool not lowered when I lower the attribute. Both augmented and non-augmented atts. Does not help changing the rating of the skill. (The pool change when raising or lowering the skill rating, just not with the correct attribute value.

It does not help lowering the skill rating to 0.

The character sheet has the same incorrect skill pools.

**To Reproduce**

Have reproduced the issue, just not reliably. Will try to update after some "research". There might have been a change of priorities involved.

**Expected behavior**
To see correct skill dice pools.

**Screenshots**
https://drive.google.com/open?id=1h4yT6lbiImUy6jIlfy0Jnct7NZIK2zvJ

**Character File**
https://drive.google.com/open?id=11GFIFc1DpHFN0HCoxBFrWuoWZG3bwXo2

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Version 5.204.0

**Additional context**
As always, thank you for a wonderful (and mostly working fine) Character generator.

**Comment by chummer5a** [comment] 2019-01-14 07:44
Duplicate of #3346

Something annoying with databindings, investigating.

**Closed by chummer5a** 2019-01-14 07:44 UTC
