### ISSUE TITLE
Current Version of the Shapeshifter

### ISSUE THREAD

**Issue by Mddd2009** [chummer5a/chummer5a#1581] opened 2017-04-16 14:14 UTC
Can you please email me a copy of the current shapeshifter the version I have is not working with the current version of chummer.

**Comment by chummer5a** [comment] 2017-04-16 14:32
Duplicate of #826. Shapeshifters are not currently supported in Chummer; if you're using a custom file, you'd have to review the file itself. At a guess, the metatypes file doesn't have a reference for the Depth attribute.

**Closed by chummer5a** 2017-04-16 14:32 UTC
