### ISSUE TITLE
Issue making drugs

### ISSUE THREAD

**Issue by MikoMikarro** [chummer5a/chummer5a#4214] opened 2020-09-07 20:29 UTC
### Environment
Crash ID: ffdd7d05-ed63-4b70-9550-5a779f9c5070
Chummer Version: 5.212.0.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: e33a9758-e8c1-46be-b54e-a5c05ce24968

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by chummer5a** [comment] 2021-01-12 01:22
Duplicate of #4215

**Closed by chummer5a** 2021-01-12 01:22 UTC
Labels: wontfix
