### ISSUE TITLE
Skills problems, one old one new (I think)

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#855] opened 2016-05-26 14:30 UTC
Version:   NewSkills release candidate v2

Maybe I should have made two diffeent issues, but the "old" problem has been a problem with chummer for a very long time and this was just to tell you it still not working properly. The new problem (which I expect is easier to fix) is the real new issue.

Expected behaviour: 
New?: Getting the right amount of skillpoints in creation mode (priority). 
Old?: Be able to break skill group without issues in career mode.

Actual behaviour:   
New?: For some reason you get skillpoints for one priority less than you have chosen. 

For example, if I have chosen B priority for skills I get 28 regular skillpoints and 2 group points. (The skillpoints I would have expected for priority C)

Old?: When breaking a skillgroup in career mod, karma is reduced but skill not raised properly.

To recreate:  
New?:  Make a character with priority skills>E. Check amount of skill points.
Old?:  Buy a skillgroup with karma. Change to career mode. Raise a skill. Save. Load.

##Helpful Fields

 Operating System: Windows 10

**Comment by joha4270** [comment] 2016-05-26 14:33
Can you elaborate your description just a bit? Or maybe just explain the logic between expected (old/new) and actual (old/new)?

**Comment by OLStefan** [comment] 2016-05-26 14:44
I've tested a bit and it seems the problem with breaking skill groups happens only, when the skill group is at over 6 ranks and you try to break it with raising a skill from that skill group. That way i can reliably reproduce that behaviour.

The other problem seems to occur everytime in priority creation. The problem is you select for example priority B for skills, but when finishing priority selection you only get skill points as if you had selected priority C.

**Comment by drakir75** [comment] 2016-05-26 15:05
To recreate skill raising problem you don't need to save/load. In career mode when trying to raise a skill (from a group) the karma is reduced but skill not raised. You will see the amount of karma spent under "Karma and Nuyen" if you save/load.

**Comment by OLStefan** [comment] 2016-05-26 19:32
Fixed in [d6e9474](https://github.com/chummer5a/chummer5a/commit/d6e94745074baae3fba0442e09ddbec9531e09fb)

**Closed by OLStefan** 2016-05-26 19:32 UTC
