### ISSUE TITLE
Feature Request: Disable "caps" when building character in "ignore rules" mode

### ISSUE THREAD

**Issue by dhyde79** [chummer5a/chummer5a#825] opened 2016-04-25 10:16 UTC
to clarify...if I'm using this to generate pre-existing characters, or higher level NPC's and I do something that raises various attributes beyond their normal starting max, the system doesn't allow me to go beyond it, nor does it allow me to place skills above a 6, if I'm having players use this to assist in converting from SR4 to SR5 characters, the conversion rules say a 6 previously should be a 10, and even with "ignore rules" checked at the start, the app doesn't allow me to input the info.  If I move it out of initial build mode to advance those to the appropriate numbers, I have to give an artificially high amount of "extra" karma, just to allow the character to finish being correctly inputted, so that the app can be used for tracking/upkeep....

**Comment by chummer5a** [comment] 2016-04-26 12:11
That's odd, I thought they were set to work that way. I'll take a look into it.

**Comment by dhyde79** [comment] 2016-04-26 13:04
For example, inputting a pair of characters that're already initiates, one grade 2 the other grade 4, the "max" magic attribute shows the appropriate max, but, I can't make the magic attribute higher than 7.  

Same with skills above 7...won't let me do it...

**Comment by chummer5a** [comment] 2016-06-06 15:26
The skills issue should be fixed as of 5.180, allowing you to increase the rating of a skill up to 12, if you've got the ignore caps rule enabled. As for your magic, have you actually initiated the characters? It's available as an optional rule; as a general rule, the ignore character creation limits is intended to bypass creation-time restrictions such as the 6-point skill cap, not to completely unbind the character from the rules.

**Comment by dhyde79** [comment] 2016-06-06 15:46
Yep, even went in and made it a grade 8 initiate just to see and a 7 magic was as high as it went...when it should allow it to be a 12 with a full essence....

**Comment by dhyde79** [comment] 2016-06-06 15:47
**correction, 14

**Comment by joha4270** [comment] 2016-06-18 08:42
On nightly i'm unable to replicate the Initiation issue either with karma or priority. 

Please reopen this issue with detailed instructions on how to reproduce this issue if your problem persist past 5.181.15

**Closed by joha4270** 2016-06-18 08:42 UTC
