### ISSUE TITLE
Max Magic for Infected

### ISSUE THREAD

**Issue by Albente** [chummer5a/chummer5a#2869] opened 2018-07-15 05:03 UTC
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.201.0
Environment: Windows 10
Runtime:  .NET 4.5.1

### Expected behaviour
In page 141 of Run Faster, it says that the maximum magic of Strain 1 or 1a HMHVV is Essence + Initiate Grade but it does not work for Nosferatu or Vampire and I can only assume the problem is the same with other Strain 1's or 1a's

### Actual behaviour
It simply reads for Initiate Grade rather than Essence.

### Steps to reproduce the behaviour
Create Human.
Add Infected: Nosferatu or Vampire.
Go into Career Mode.
Add Karma.
Add Max Essence Improvement (To any amount above 6)
Attempt to press grey '+' button with no initiate grade.
Add Initiate grade.
Only able to press '+' button once.

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment] 2018-07-16 07:04
More or less a duplicate of #2720

**Closed by chummer5a** 2018-07-16 07:04 UTC
