### ISSUE TITLE
 Issue: - Chummer5 crashes while holding Ctrl

### ISSUE THREAD

**Issue by Quintar** [chummer5a/chummer5a#1942] opened 2017-10-05 18:56 UTC
### Environment
Crash ID: 6716332c-71fd-4c6d-99d1-0372f336b770
Chummer Version: 5.195.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000

### Expected behaviour
Nothing special is happening

### Actual behaviour
crash

### Steps to reproduce the behaviour
Holding <Ctrl> while having the mouse rolling over the place (Chummer is in the foreground) with Discord in the background (Ctrl is the push-to-talk key)

**Comment by DelnarErsike** [comment] 2017-10-05 19:14
Cannot reproduce. Holding down Ctrl with the latest nightly of Chummer open in the foreground and Discord running in the background does not cause Chummer to crash. Holding down Discord's push-to-talk key also does not cause Chummer to crash. I suspect the problem is strictly with your specific setup.

Please respond if you are able to reproduce the crash, otherwise I will close this issue in 72 hours.

**Closed** 2017-10-08 21:37 UTC
Labels: bug: application error, response pending
