### ISSUE TITLE
Skill tab display cropped

### ISSUE THREAD

**Issue by Thanael0** [chummer5a/chummer5a#1409] opened 2017-02-07 14:24 UTC
### Environment
Chummer Version: 5.190.0
Environment: Windows 7
Runtime: not sure (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Skills should be readable

### Actual behaviour
The skill tab is cropped at the left and resizing the main window and scrolling do not help.

Screenshot:  http://s000.tinyupload.com/?file_id=09942919180277418135

**Comment by chummer5a** [comment] 2017-02-07 14:32
Chummer currently isn't very DPI-aware; if you change the display size back down to 100% it'll display properly. You *might* have some success if you disable display scaling. To do this, right-click on chummer.exe and click on Properties. On the Compatibility tab, select Disable Display Scaling On High DPI Settings, and then click OK. Probably won't help, but it's worth a shot.

**Comment by chummer5a** [comment] 2017-02-07 14:35
Duplicate of #1187.

**Closed by chummer5a** 2017-02-07 14:35 UTC
