### ISSUE TITLE
Life Modules save character too many skills, wont save correctly

### ISSUE THREAD

**Issue by E-Strange** [chummer5a/chummer5a#528] opened 2015-11-23 00:59 UTC
When you make a character using life modules, it seems to work rather well, but when you save it and reopen it, all the skill numbers are too high.

**Comment by datasteal** [comment] 2015-12-02 12:25
+1
What I'm seeing is that if you save, close the character, and re-open it has recalculated the Life Modules skill points on top of what was previously saved. (ie if you have 2 points in Archery from the module after you save and re-open the character this becomes 4)
And there is no end to this. If you save again and re-open it increases it again.

**Comment by chummer5a** [comment] 2015-12-02 12:46
@joha4270 was working on a rewrite of the skills that should resolve this, but I'm not sure what the eta is for it. I'll see if I can hotfix it in some way.

**Comment by joha4270** [comment] 2016-06-29 10:18
I'm unable to reproduce this in the latest, so i'm going to close this issue.

**Closed by joha4270** 2016-06-29 10:18 UTC
Labels: bug: application error
