### ISSUE TITLE
Crashing upon clicking the armor tab in street gear

### ISSUE THREAD

**Issue by Rinnolk** [chummer5a/chummer5a#2423] opened 2018-01-31 19:21 UTC
### Environment
Chummer Version: 197.17 and 197.18
Environment: W10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Not crashing

### Actual behaviour
Crashing 
https://i.imgur.com/LURou8r.png

### Steps to reproduce the behaviour
Click on street gear, click on clothing and armor.

### Link to affected character file
https://drive.google.com/open?id=1D_bpy1JVKqNHW7SxgcyIGz5rkNrkugTu

**Comment by DelnarErsike** [comment] 2018-01-31 19:26
Duplicate of #2419.

**Closed by DelnarErsike** 2018-01-31 19:26 UTC
