### ISSUE TITLE
Program Suite

### ISSUE THREAD

**Issue by chummer5hasanerror** [chummer5a/chummer5a#3317] opened 2018-12-31 17:22 UTC
This one is SUPER EASY

I want an item that is listed under the 'Hacking Programs' Dropdown menu called 'Full Suite' or 'Everything' or something to that effect.
This item has a base Nuyen cost of around 9k (the precise amount of EVERY hacking program in game added together)
This item, when purchased, will Create a Location in the Gear Tab, called 'Hacking Programs'
This item, when purchased, will populate the Location called 'Hacking Programs' with a single instance of EVERY HACKING PROGRAM in-game.
This item, when purchased, will save users almost 5 minutes of attempting to add each Hacking Program individually.
This item will NOT be listed under PACKs or stashed elsewhere in the program; it will be listed under 'Hacking Programs' in the Gear Tab, as it is just the ability to purchase every hacking program with a single interaction

**Comment by chummer5a** [comment] 2020-01-09 03:21
Not going to do that. Purchasing multiple items is a duplicate of #2566

**Closed by chummer5a** 2020-01-09 03:21 UTC
Labels: feature
