### ISSUE TITLE
SURGE qualities count against actual positive and negative quality limits

### ISSUE THREAD

**Issue by PhotonSilencia** [chummer5a/chummer5a#2595] opened 2018-03-13 08:56 UTC
### Environment
Chummer Version: 5.198.0
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

The title says it, basically.
Picking SURGE III and then trying to add metagenetic qualities ends up not working at all.
Both positives and negatives get added to the regular positive and negative qualities and limits, and reduce/increase standard karma respectively. 
Checking for character validity also does not at all check if the SURGE qualities balance out.

**Comment by chummer5a** [comment] 2018-03-13 10:47
Should be resolved in current nightly builds.

**Comment by PhotonSilencia** [comment] 2018-03-13 17:12
It is not.

**Comment by MaraFaye** [comment] 2018-03-18 13:31
I can't reproduce it either, Aside from the annoying hardcoded point limit it works fine for me in 5.18.36.

**Comment by chummer5a** [comment] 2018-03-18 13:36
Actually as of the current nightly builds, you should be fully capable of adjusting how many points you receive to play with from a Changeling quality using an amend or override file. Just replace the metageneticlimit value with whatever you want. The marry-up behaviour with requiring that the quality types be within 1 of each other is still coded behaviour, but I've never seen anyone using house rules that would need an alteration of that yet.

**Closed** 2018-03-19 08:18 UTC
Labels: bug: application error, response pending
