### ISSUE TITLE
Cant buy weapon accessories for slots that already have an accessory.

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#4765] opened 2022-04-11 02:13 UTC
As an example add an AK-97 and buy a silencer for it on the barrel. This uses up the barrel slot. At this point, installed or not, no barrel slot mods are shown in the list.
I would expect we can still buy those modes and  just not have them installed. Maybe add a show unavailable button or something to the window to unhide mods that go to already used slots.

**Comment by DelnarErsike** [comment] 2022-04-11 03:11
Duplicate of #3469.

**Closed by DelnarErsike** 2022-04-11 03:11 UTC
