### ISSUE TITLE
Cyberlimbs with Connector

### ISSUE THREAD

**Issue by Balkahaz** [chummer5a/chummer5a#1092] opened 2016-09-11 14:03 UTC
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)
### Environment

Chummer Version: 5.183
Environment: Windows 10 64Bit
Runtime: .net 4.5
### Expected behaviour

A possebility to Mark Optional Cyberlimbs as not Connected and don't lose Essence for an Optional Cyberlimb
### Actual behaviour

Essence lose for 2 Cyberlimbs with Modual Connector.
### Steps to reproduce the behaviour

Add two Cyberlimbs for Example 2 Right Arms and add the Modual Connector.

**Comment by chummer5a** [comment] 2016-12-05 05:08
Duplicate of #900.

**Closed by chummer5a** 2016-12-05 05:08 UTC
Labels: enhancement/feature request
