### ISSUE TITLE
Cybereyes Mods Not Showing on PDF

### ISSUE THREAD

**Issue by Shadehawke** [chummer5a/chummer5a#2273] opened 2018-01-08 06:23 UTC
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (What version of chummer are you running? 5.196.0
Environment: (Operating system here. If it persists over multiple OS's list them all) Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1) .NET 4.7

### Expected behaviour
When saving to HTML or PDF, under Cyberware the Mods for my Cybereyes should all show up.

### Actual behaviour
When saving to HTML or PDF, Cybereyes Basic System shows up, but it only shows the default Image Link. None of the mods that were added are showing.

### Steps to reproduce the behaviour
Cybereyes Basic System Any rating, then add mods

### Link to affected character file
Chummer File - https://drive.google.com/open?id=1kn1CUYi0Em88uA9oizsDEdvGeBtB9_5k

PDF - https://drive.google.com/open?id=1MGjN_PwylkIx2-3PyqGo9gkaS_7wemUn

**Comment by DelnarErsike** [comment] 2018-01-08 17:40
AFAIK, this issue is a duplicate of #2231, which has already been fixed. However, I'm currently reviewing an issue related to this character, namely whether you are allowed to add vision enhancements as gear plugins to cybereyes, or if it's restricted to cyberware plugins. You should probably replace those gear plugins with 'ware plugins...

**Closed by DelnarErsike** 2018-01-08 17:40 UTC
