### ISSUE TITLE
Multiple entries in Mental Limit modifiers

### ISSUE THREAD

**Issue by cfresquet** [chummer5a/chummer5a#2975] opened 2018-09-08 19:08 UTC
![screencap](https://user-images.githubusercontent.com/13633603/45257715-74582980-b35f-11e8-9136-03fff51ba132.jpg)

Also - even if I hand-edit the save file to remove the multiple entries, the next time I open the printable character sheet they get recreated and come back again.

### Environment
Chummer Version: latest build
Environment: Win10
Runtime: .NET 4.5.1

### Expected behaviour
Vision Enhancement modifier for perception should only list once

### Actual behaviour
modifier lists 7 additional times

### Steps to reproduce the behaviour
load attached character, look at character sheet

### Link to affected character file
[Echo-test.zip](https://github.com/chummer5a/chummer5a/files/2363637/Echo-test.zip)

**Comment by DelnarErsike** [comment] 2018-09-09 18:54
Oof, this issue was a weird one. It'll be fixed in my next commit, but unfortunately, there's no way to easily clean affected characters without manually going in and fixing things. The bug was caused by three bits of code in Chummer5, the most important of which was a legacy conversion code that is supposed to regenerate deactivated improvements for unequipped gear, but due to a wrong check, it was regenerating improvements for non-legacy cases as well.

I've gone through and fixed your character file, though you should wait until the next nightly (built roughly 5 hours after the time this reply is posted) before saving the character again, otherwise the duplicates will start appearing:

[Echo-test.zip](https://github.com/chummer5a/chummer5a/files/2364539/Echo-test.zip)

**Closed** 2018-09-09 18:59 UTC
Labels: bug: application error
