### ISSUE TITLE
crash while upping magic attribute

### ISSUE THREAD

**Issue by TheL1ne** [chummer5a/chummer5a#3723] opened 2019-06-21 21:29 UTC
### Environment
Crash ID: 926ec535-e0e5-4433-b4cf-e069a020318a
Chummer Version: 5.207.0
Environment: Windows 10 Education
Runtime: 4.0.30319.42000

### Expected behaviour
was changing attributes and wanted to go from 4 magic to 5

### Actual behaviour
crashed when I used the up arrow next to the field

### Steps to reproduce the behaviour
Was unable to reproduce

**Comment by DelnarErsike** [comment] 2019-07-08 12:44
It's hard to debug a crash if you are unable to reproduce it. I'm closing this issue for now, but if/when you are able to reproduce this crash, please re-open this issue.

**Closed by DelnarErsike** 2019-07-08 12:44 UTC

**Comment by ArchonMegalon** [comment] 2019-07-08 12:48
Just a sidenote: in the current nightlies you can set an option to enable logging and upload the logs. When you experiance a crash like this and report it, it should include a "Installation ID", that should help us find the "real" corresponding log-message. 

Of course that's only for future problems - won't help in this instance!

**Comment by TheL1ne** [comment] 2019-07-09 09:57
Was using a stable release and no nightly. Was actually only reporting it because the builin funtion brought me here.
