### ISSUE TITLE
Can't save changes when changing Lifestyles

### ISSUE THREAD

**Issue by Fersoltil** [chummer5a/chummer5a#4269] opened 2020-12-08 07:44 UTC
[5.213.0, de-DE]

Whenever I make changes to existing lifestyles or add new ones, Chummer5 throws "Chummer5 has encountered an Error".

**To Reproduce**
1. create new character
2. add  a Lifestyle
3. click save

**Expected behavior**
File saves.

**Desktop (please complete the following information):**
 - OS: Win10 v2004 b19041.630
 - Version 5.213.0 de-DE

**Comment by Fersoltil** [comment] 2020-12-08 07:53
Update: Probably language file issue. Saves fine in en-EN

**Comment by DelnarErsike** [comment] 2020-12-09 10:37
Duplicate of #4264, closing unless confirmed otherwise.

**Closed** 2020-12-09 10:37 UTC
