### ISSUE TITLE
[Feature Request] Street Scum/HIgh Life implementation

### ISSUE THREAD

**Issue by HaikenEdge** [chummer5a/chummer5a#369] opened 2015-09-06 19:07 UTC
Would it be possible for Street Scum and High Life campaign-styles to be implemented into a future version of Chummer 5A? 

Both are covered on page 354 of the core book, with Street Scum having starting priorities of BCDEE or CCDDE, and High Life having starting priorities of AABCC and no availability limits.

**Comment by joha4270** [comment] 2015-09-06 19:10
Duplicate of #357, except for a single entry in a data file

**Closed by joha4270** 2015-09-06 19:10 UTC
