### ISSUE TITLE
Shaman Tuxedo asks for Spell Category instead of Spirit Type

### ISSUE THREAD

**Issue by ArchonMegalon** [chummer5a/chummer5a#4599] opened 2021-11-03 14:02 UTC
Cutting Aces Page 143:

RAW: "Each set is designed to affect one specific type of spirit that tradition is capable of conjuring."

It asks for the Spell Category.

**Comment by larryw24** [comment] 2021-11-24 07:59
Is this a duplicate of Bug #4225?  https://github.com/chummer5a/chummer5a/issues/4225

**Closed** 2022-01-29 13:31 UTC
Labels: bug: data file content
