### ISSUE TITLE
Reduce Street Cred

### ISSUE THREAD

**Issue by Teksura** [chummer5a/chummer5a#3571] opened 2019-04-12 04:23 UTC
**Is your feature request related to a problem? Please describe.**
Better Than Bad has options for using Street Cred in various ways. however, chummer does not currently support this, and the only method is paying 2 street cred to reduce notoriety by one.

**Describe the solution you'd like**
Allow either an option to set the box next to street cred to a negative number to allow reducing it, or allow an option to spend street cred without it affecting notoriety.

**Comment by darksnakezero** [comment] 2019-09-22 11:58
Duplicate of #3648

**Closed** 2019-09-23 00:17 UTC
Labels: feature
