### ISSUE TITLE
Chummer Crash on Character Creation after sum to ten

### ISSUE THREAD

**Issue by GermanDarkShadow** [chummer5a/chummer5a#4951] opened 2022-10-28 12:18 UTC
**Describe the bug**
Chummer crashes if I create a new character

**To Reproduce**
Create new Character --> Sum to Ten ---> Pick everything --> Ok ---> Crash

**Expected behavior**
Open the character creation after "Sum to ten" 

**Screenshots**
None, crashes without failure message

**Character File**
None, cause cant create

**Desktop (please complete the following information):**
Windows 10 21H2 Build 19044.2006

**Additional context**
Chummer Crash reporter:
This file contains information on a crash report for Chummer5A.
You can safely delete this file, but a developer might want to look at it.
System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
   bei System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   bei Chummer.frmSelectBuildMethod..ctor(Character objCharacter, Boolean blnUseCurrentValues) in C:\projects\chummer\Chummer\Character Creation\frmSelectBuildMethod.cs:Zeile 63.
   bei Chummer.frmChummerMain.ShowNewForm(Object sender, EventArgs e) in C:\projects\chummer\Chummer\frmChummerMain.cs:Zeile 1237.
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   bei System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   bei System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bei System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   bei System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   bei System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   bei System.Windows.Forms.Application.Run(Form mainForm)
   bei Chummer.Program.Main() in C:\projects\chummer\Chummer\Program.cs:Zeile 485.
Crash id is 22c637b5-3e63-47f8-ab47-5f0792ae7d70
Crash working directory is C:\Users\XXX\AppData\Local\Temp\chummer_crash_133114319229506850

Please be aware that the Username has been changed on this report

Thank you and regards

**Comment by DelnarErsike** [comment] 2022-10-28 23:48
Can't seem to replicate this issue in the latest Nightly.

**Comment by DoomlordSoul** [comment] 2022-10-31 09:25
Have a Similar Problem, I am using V. 5.224.0 choose 'Full House (Zehn-Punkte-Option, Deutsch)' (in English is it '(Sum-To-Ten, German)'), I choose after that the Trait Drake (Seedrake) Enter the Wanted Value and after that comes the Crash, without any Message, and it just happens if I choose Sum-To-Ten

**Comment by GermanDarkShadow** [comment] 2022-10-31 10:32
Its a good indication, Im also using the german data set.
Has Chummer Problems if it is used in an AD managed Network maybe?

**Comment by Jydaxprime** [comment] 2022-11-12 22:23
Started having a similar problem, crashes on trying to assign attributes in Priority creation too.

**Comment by DelnarErsike** [comment] 2022-11-14 01:18
I definitely cannot reproduce this issue in the Nightly, and I believe the crash related to it was fixed in commit 821c07d781efc54726c79a703b8d31ebc036bafa. Closing this issue, please re-open if you can successfully reproduce the crash in the current Nightly build(s).

**Closed by DelnarErsike** 2022-11-14 01:18 UTC
Labels: bug: C#, response pending
