### ISSUE TITLE
Feature Request: To be able to edit Fake SINs while in Create mode

### ISSUE THREAD

**Issue by Zitchas** [chummer5a/chummer5a#2582] opened 2018-03-10 22:15 UTC
### Desired behaviour
While in create mode, it would be helpful if people could edit the names on their fake SINs. Of course, once the character is moved into career mode this value should be locked in. 

### Actual behaviour
Once the name is entered into the value field, it is locked and can no longer be changed. 

### Benefit provided
When creating a character I often can't think of good names to use for the fake SIN. Or have the specific country nailed down, either. Being able to edit this while in create mode would let me purchase the fake SIN and licenses with a placeholder name without having to re-purchase all the attached licenses later on once I figured out what I wanted the name to be.

**Comment by ordeiberon** [comment] 2018-09-25 11:39
Seconding. I like to come up with extra fluff or better names, but dislike having to re-add all of the fake licenses again. This seems identical to request #2850 that mentions editing of Many qualities like Addiction, Prejudice, etc. as well.

**Comment by chummer5a** [comment] 2018-09-28 09:49
Duplicate of #2850

**Closed by chummer5a** 2018-09-28 09:49 UTC
Labels: enhancement
