### ISSUE TITLE
Vehicle/drones not calculating dice pool correctly

### ISSUE THREAD

**Issue by oddmage** [chummer5a/chummer5a#938] opened 2016-06-18 20:32 UTC
Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.
I add a drone, add a mount, then a weapon, check the sheet and it says dice pool of 0. I try adding the Pilot autosoft and the Autosoft for targetting. I've tried Autosoft (Rating 6) (Targetting) and Autosoft (Rating 6) (Targetting (weapon name)), but neither seems to work.
Someone in a thread on reddit commented on a rigger he has and his [sheet ](https://drive.google.com/drive/folders/0B_nRB27IrCKafnRLNFl4Yk4teGRlZlZ1U3g0Wlkta29QRmltYS16eUl4ZGprRjFmelVobDQ)is obviously chummer and is working off his RCC. I tried the RCC too and didn't have much luck.

### Chummer Version
5.181.14

### Expected behaviour
Drones should use Pilot + Targetting Autosoft

### Actual behaviour
DIce pool shows 0

### Steps to reproduce the behaviour
Add a drone or vehicle, try and add targetting autosoft.

### Link to affected character file
NA

**Comment by joha4270** [comment] 2016-06-25 08:38
duplicate of #103 so i'm closing this.

**Closed by joha4270** 2016-06-25 08:38 UTC
