### ISSUE TITLE
Capsule rounds taking up too many doses of chemical

### ISSUE THREAD

**Issue by Morcleon** [chummer5a/chummer5a#1562] opened 2017-04-04 23:33 UTC
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.192.0
Environment: Windows 8.1
Runtime: .NET 4.5.1

### Expected behaviour
Capsule rounds should require 1 dose of chemical per 5 rounds.

### Actual behaviour
Capsule round costs indicate that they are taking up 1 dose per round.

### Steps to reproduce the behaviour
Add any chemical to a capsule round and check the price.

### Link to affected character file
https://www.dropbox.com/s/nxmwvm5czdy61p5/Cerise%20Belrose%20-%20Gun%20Adept.chum5?dl=0

**Comment by chummer5a** [comment] 2017-04-05 05:23
Duplicate of #773. Chummer currently isn't coded to interact nicely with child items that don't have a 1:1 relationship with the parent, due in large part to how the ammo system was implemented previously. 

As a workaround, you can use the markup function while in career mode to reduce the nuyen percentage to whatever makes sense for the given amount of rounds required, but it gets quirky when you try to reload it.

**Closed by chummer5a** 2017-04-05 05:23 UTC
Labels: duplicate
