### ISSUE TITLE
Can't add Cyber-/ Bioware above grade Alpha

### ISSUE THREAD

**Issue by MaraFaye** [chummer5a/chummer5a#2738] opened 2018-05-08 19:46 UTC
### Environment
Chummer Version: 5.200.2
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
The dropdown shows the options for Beta and Deltaware, adding them adds the selected item in the chosen grade.

### Actual behaviour
Beta, Delta and Gamma grade ware are added as standard ware, even when character creation rules are to be ignored.

### Steps to reproduce the behaviour
Try to add ware to a char in creation mode.

### Link to affected character file
(Enter text here)

**Comment by Azure-Fang** [comment] 2018-05-09 02:57
From my experience, the 'ware is being properly added and essence/price is adjusted, but does not properly show its grade in the on-sheet box, since the on-sheet dropbox only shows "standard", "used", "alphaware", and "omegaware".

**Comment by chummer5a** [comment] 2018-05-09 06:55
Duplicate of #2661. I think I know what's going on with it, shouldn't be a problem to sort out.

**Closed** 2018-05-11 13:52 UTC
Labels: bug: application error, duplicate
