### ISSUE TITLE
 Issue: - Crash on adding Ritual after Invocation Art has been selected.

### ISSUE THREAD

**Issue by Beaumis** [chummer5a/chummer5a#1740] opened 2017-06-22 16:58 UTC
### Environment
Crash ID: c0ef4700-bc8f-4b1a-8a68-ebe813acf3b8
Chummer Version: 5.193.0
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
Chummer should open a selection dialogue offering Summon Ally Spirit and Summon Great Form Spirit Rituals.

### Actual behaviour
Chummer crashes.

### Steps to reproduce the behaviour
Create Character
Add Initiation Grade
Add Invocation Art
Right click grade and select add Ritual
Chummer crashes

**Comment by chummer5a** [comment] 2017-06-23 03:34
Can't reproduce it. What's the error message say?

**Comment by Beaumis** [comment] 2017-06-23 05:56
Crash followup id = f3284f6d-6924-4387-916c-5e15841151f3

"Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt" (German Windows, rough translation:
The objectreference was not assigned to an objectinstance

I also send an Error Report. Not sure how to get to that though.

**Comment by Beaumis** [comment] 2017-06-23 05:59
[attributes.txt](https://github.com/chummer5a/chummer5a/files/1096884/attributes.txt)
[exception.txt](https://github.com/chummer5a/chummer5a/files/1096885/exception.txt)

When looking at the exception.txt, it refers to to a different path than the one chummer is actually in. Is that normal? The path doesn't exist on my PC.

**Comment by chummer5a** [comment] 2017-06-23 06:00
Build reference, we can't strip out the code for that. I think I know what's going on, I'll have it fixed in the next few hours.

**Comment by Beaumis** [comment] 2017-06-23 06:08
Thank you so much for all your hard work. You're awesome. :)

**Comment by chummer5a** [comment] 2017-06-24 11:59
Nope, still can't replicate it. What else is specific to it? Is it a completely new character? Nothing else added?

**Comment by Beaumis** [comment] 2017-06-24 19:42
It happened on a new character as well as old ones.

Yesterday, I downloaded a nightly build at 18:04 GMT +2. It was the latest at that point and the crash occurred with both old and new characters (new one tested with priority system, nothing distributed just straight into career, add initiation, add art Invocation, add ritual -> crash)

However, I just downloaded the latest nightly build and tried again. The crash did not occur and the rituals menu opened as normal. Since the last nightly build is one 3 hours old at the time of writing, something between those two builds seems to have fixed the issue. 

So even if you can't replicate it, thanks a lot for fixing it. :)

**Closed** 2017-06-25 01:41 UTC
Labels: bug: application error
