### ISSUE TITLE
Technomancer Daemon listed as echo

### ISSUE THREAD

**Issue by Syrasar** [chummer5a/chummer5a#2963] opened 2018-09-02 02:45 UTC
a Technomancer Daemon is part of their Streams or in other words part of their Positive qualities and not an
echo

Suggestions: other then removing it from the echo (only cyberadept seems to be there so far) using the method of mentor spirits to add the Daemon Effects to the complex forms tab might be the most simplistic method of dealing with the issue

Version used: chummer nightly 5.202.20

**Comment by chummer5a** [comment] 2018-09-02 12:35
Yeah, it was included in that way as a quick and dirty proxy. I need to implement something to handle the initiate grade shenanigans for streams.

**Comment by chummer5a** [comment] 2018-09-02 13:51
Duplicate of #2941

**Closed by chummer5a** 2018-09-02 13:51 UTC
