### ISSUE TITLE
Issue: - PLEASE ENTER DESCRIPTION HERE

### ISSUE THREAD

**Issue by BrandonVSC** [chummer5a/chummer5a#4247] opened 2020-10-26 06:54 UTC
### Environment
Crash ID: fbcfe2b5-bbe6-4d5a-857e-2fb06d77ae6c
Chummer Version: 5.212.185
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 579f29c7-80fa-428a-82e9-c6828845909c

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by DelnarErsike** [comment] 2020-11-03 12:21
Duplicate of #4240

**Closed by DelnarErsike** 2020-11-03 12:21 UTC
