### ISSUE TITLE
Qualities added to refine relationship with a contact

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#930] opened 2016-06-16 00:14 UTC
Run Faster p 178 adds new qualities to refine the relationship between a character and a contact. These include Blackmail and Family. Can these be added toChummer5 ?

**Comment by chummer5a** [comment] 2016-06-16 12:56
Duplicate of existing issue: https://github.com/chummer5a/chummer5a/issues/218

Shouldn't take much to implement, just busy with other issues at the moment.

**Closed by chummer5a** 2016-06-16 12:56 UTC
