### ISSUE TITLE
Adding two bioware "Right" retractable claws, Crashes the app

### ISSUE THREAD

**Issue by Jtull1127** [chummer5a/chummer5a#4817] opened 2022-06-01 02:06 UTC
**Describe the bug**
Adding two sets of retractable claws "right' Causes a crash

**Comment by chummer5a** [comment] 2022-06-01 13:05
You shouldn't be able to do that unless you have two sets of arms. Otherwise unable to reproduce the issue.

**Comment by Anon5342** [comment] 2022-06-06 07:54
Back in April I reported a [similar issue](https://github.com/chummer5a/chummer5a/issues/4776) which would likely cause this same problem. I was told it was fixed in the nightly. That was a bug in version 5.222.0. It was released on Feb 19th. It is still the "current" release of Chummer.

**Comment by chummer5a** [comment] 2022-06-14 10:49
Closed presuming milestone issue resolved in nightlies.

**Closed by chummer5a** 2022-06-14 10:49 UTC
