### ISSUE TITLE
As a result of clicking a skill tab, chummer crashes. 

### ISSUE THREAD

**Issue by wakiko** [chummer5a/chummer5a#933] opened 2016-06-16 15:50 UTC
Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version
chummernightly

### Expected behaviour
skill tab click

### Actual behaviour
An error message comes out. A skill list does not come out. situation like an attached file. 
![error](https://cloud.githubusercontent.com/assets/19861325/16123282/5ad73bce-3425-11e6-92e5-11e2d844b3b5.jpg)
[chummerlog.txt](https://github.com/chummer5a/chummer5a/files/318793/chummerlog.txt)

### Steps to reproduce the behaviour
(Enter text here)

### Link to affected character file
(Enter text here)

**Comment by DoStuffZ** [comment] 2016-06-16 20:08
Seems to be linked with #924

**Comment by joha4270** [comment] 2016-06-17 10:51
Might be fixed 5.181.12 but i cannot say for sure. With your instructions for reproduction i'm unable to reproduce, but your instructions are rather sparse. 

If the issue persists, please provide the following
Initial state of chummer (version, language, enabled books) and a keypress by keypress process to make it crash.

**Comment by wakiko** [comment] 2016-06-17 11:56
I used cummer5.181.2. But I crashed. The situation has not changed. 
A use book is "run & gun""clome flesh""streetgrimoire""run faster""date trails." 
 An input language is Japanese. The initial state of an input key is also Japanese. 
OS is Windows 7. 
NET Framework 4.6. 
Please help me if you please.

**Comment by joha4270** [comment] 2016-06-17 11:57
.2 or .12?

**Comment by wakiko** [comment] 2016-06-17 11:58
sorry 12

**Comment by joha4270** [comment] 2016-06-17 12:18
Not able to reproduce on windows 10 with Chummer5a set to Japanese

Going to install a [virtual machine](https://en.wikipedia.org/wiki/Virtual_machine) and see if i can change reproduce it on a japanesse system, without understanding the language, but i'm not particularly hopeful.

.13 is up which isn't going to fix your problem, but contains a little more information on why it didn't create a crash report. Having the crash report would be helpful

**Comment by Sceptically** [comment] 2016-06-18 15:08
I'm seeing the same error message, but with English as the interface language. This happens for me when clicking on the skills tab, or when adding pretty much any quality. I'm using the current nightly build (5.181.17) with Mono on Debian Linux.

**Comment by joha4270** [comment] 2016-06-19 15:14
@wakiko Can i have you try again after installing nightly 5.181.25? 

Think i found out why crash reports don't work and having one of them would be helpful in resolving this bug. 

If it works, it should mention a "crash followup id", please share it here if you are successful

**Comment by DoStuffZ** [comment] 2016-06-20 08:06
There seems to be a mix up of Knowledge points and special points (karma/magic/resonance). Twice I have helped players create new chummers, each time the number of knowledge points gets displayed as "you haven't spent the special points",

**Comment by joha4270** [comment] 2016-06-21 08:23
@DoStuffZ I don't quite see how that is related to _**this**_ issue.

**Comment by wakiko** [comment] 2016-06-22 16:54
[
[chummerlog.txt](https://github.com/chummer5a/chummer5a/files/328353/chummerlog.txt)
](url)
ver5.18129
It is log which came out when 5 was used. 
I will crash, it clicks a skill tab. 
This situation is not different from before.

**Comment by joha4270** [comment] 2016-06-22 16:57
Still just saying "failed to create crash report"?

Not a larger message and/or a window popping up saying chummer has crashed and asking what you was doing?

**Comment by joha4270** [comment] 2016-06-25 08:31
Seeing that nobody over at #941 is responding, i would like to impose one of the people who has this issue to test the latest nightly. 

I think it has been fixed, but i'm unable to reproduce on my own so i'm unable to test it.

Sorry for being slow fixing this rather major issue, but i'm shooting a little in the dark.

**Comment by Sceptically** [comment] 2016-06-25 08:41
Works for me with v5.181.34

**Comment by joha4270** [comment] 2016-06-28 16:01
We have received reports that this issue is fixed in nighties. Unless or until we get contrary reports i'm going to close this issue.

**Closed by joha4270** 2016-06-28 16:01 UTC
