### ISSUE TITLE
program crash by edit the options (equal behavior in a different windows)

### ISSUE THREAD

**Issue by PSI1919** [chummer5a/chummer5a#2055] opened 2017-11-15 10:54 UTC
### Environment
Crash ID: c87a0583-4f42-4759-8031-8663328be41d
Chummer Version: 5.195.71
Environment: Windows 7 Ultimate
Runtime: 4.0.30319.42000

### Expected behaviour
no crash :)

### Actual behaviour
every test to edit the options (books, rules etc) led to a program crash with press the "ok" - button

### Steps to reproduce the behaviour
edit the options and press enter

**Comment by OLStefan** [comment] 2017-11-15 10:56
Duplicate of #2054

**Closed by OLStefan** 2017-11-15 10:56 UTC
