### ISSUE TITLE
knowledge skills spec. during creation

### ISSUE THREAD

**Issue by seppestuyck** [chummer5a/chummer5a#185] opened 2015-04-30 15:24 UTC
when you take a specialization instead of using a point it doubles the cost of the ranks you have in that skill

p.s. : just noticed that there is a similar problem reported, if it turns out to be the same, im sorry for the double post :P

**Comment by chummer5a** [comment] 2015-04-30 15:45
Duplicate of #184. Hotfixed in 5.165.1.

**Closed by chummer5a** 2015-04-30 15:45 UTC
Labels: bug, duplicate
