### ISSUE TITLE
Existing Characters cant print

### ISSUE THREAD

**Issue by chummer5hasanerror** [chummer5a/chummer5a#2130] opened 2017-12-03 19:15 UTC
### Environment
Chummer Version: .94
Environment: w7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Press Print Button, program opens a new window, compiles info, then displays the filled out sheet.

### Actual behaviour
Press Print Button.  Program opens new window.  Window is empty/blank and displaying a sheet

### Steps to reproduce the behaviour
Load career mode character made in previous version.  Press Print

**Comment by chummer5a** [comment] 2017-12-04 09:17
Can't replicate it in current builds. Got any more detail about the cause, or examples of an affected character?

**Comment by Lochabar** [comment] 2017-12-05 02:43
I think this is the problem:
![blank sheet](https://user-images.githubusercontent.com/17562417/33587248-15c46976-d965-11e7-9dfe-87d515dc905e.png)

Having opened this character
[Character file.zip](https://github.com/chummer5a/chummer5a/files/1529520/Character.file.zip)

Clicked print and the character viewer opened with the above blank page. "Shadowrun 5" is my default character. Simply selecting the character sheet again presents the sheet correctly. This is happening with 5.195.96, and with prior versions.

**Comment by chummer5a** [comment] 2017-12-05 03:48
Hmm, it loads for me after about half a second of whitespace.

**Comment by DelnarErsike** [comment] 2017-12-05 17:34
Could you try again in 5.195.97 or later? I changed some things around, so you should see which part of the character printing process is causing Chummer to hang.

**Comment by Lochabar** [comment] 2017-12-06 03:04
After clicking the print button
- seconds of the blank page
- "Loading Characters" displayed for several seconds
- seconds of blank page
- "Generating Sheets" displayed for several seconds
- back to the blank page for 15-20 seconds before the character sheet displayed.

It seems the delay happens the first time the print button is used after Chummer is started. After that "Loading Characters", "Generating Sheets" quickly pass and the sheet shows quickly.

**Comment by DelnarErsike** [comment] 2017-12-08 00:27
Based on that process, I feel I can safely say that it is extremely likely that the issue is caused by the particular installation of Internet Explorer on the machine using Chummer5, and not anything specific in Chummer5's code (besides a reliance on the WebBrowser WinForms control, of course, which is why Internet Explorer is even relevant).

I am closing this issue for now.

**Closed by DelnarErsike** 2017-12-08 00:27 UTC
Labels: bug: application error

**Comment by Lochabar** [comment] 2017-12-08 01:05
I don't use I.E. so it is plain vanilla, no extensions, etc. So can be wrong with it?

**Comment by DelnarErsike** [comment] 2017-12-08 01:10
It doesn't matter what you use or don't use. Chummer uses WinForms' WebBrowser control, which will always use whatever version of Internet Explorer is installed on the machine. If that runs slow under your configuration, then the character sheet preview screen itself (which is essentially an Internet Explorer window without any buttons, tabs, or address bars) is going to run slowly.
