### ISSUE TITLE
Issue: - Chummer crashes at activating German Data Changes

### ISSUE THREAD

**Issue by Zorunel** [chummer5a/chummer5a#4517] opened 2021-07-23 21:58 UTC
### Environment
Crash ID: b1dd99a4-6591-4de3-934e-06fc39a2f97f
Chummer Version: 5.214.130
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: ae8c032e-9dc4-4b64-b0ce-778929a2a6d0

### Expected behaviour
Chummer doesn't crashes

### Actual behaviour
Default Settings activated, Chummer crashes on clicking German Data Changes

### Steps to reproduce the behaviour
Activate Default Settings and click on German Data Changes
[chummer_crash_132715508396030564.txt](https://github.com/chummer5a/chummer5a/files/6871418/chummer_crash_132715508396030564.txt)

**Comment by DelnarErsike** [comment] 2021-07-23 23:56
Duplicate of #4513.

**Closed by DelnarErsike** 2021-07-23 23:56 UTC
