### ISSUE TITLE
Cannot buy months of lifestyle during play mode

### ISSUE THREAD

**Issue by HaikenEdge** [chummer5a/chummer5a#417] opened 2015-09-24 18:40 UTC
Not sure what's causing it, but whether I try to buy months of a lifestyle for an existing lifestyle, or create a new lifestyle, the option to buy months of a lifestyle, despite having the money to do so, remains grayed out.

**Comment by chummer5a** [comment] 2015-09-24 21:27
Career or creation?

**Comment by HaikenEdge** [comment] 2015-09-24 21:29
Career

**Comment by chummer5a** [comment] 2015-09-25 14:09
Hrm. Can't replicate it. Can you upload your character file somewhere?

**Comment by HaikenEdge** [comment] 2015-09-25 14:15
[Here you go](http://www.mediafire.com/download/bcvibb52gg9hhd1/Crow.chum5)

**Comment by cfresquet** [comment] 2015-09-25 18:38
I noticed the same problem as well.  Let me know if you need a 2nd example.

**Comment by chummer5a** [comment] 2015-09-27 14:55
Hrm. So the issue is that your lifestyle doesn't have a baselifestyle assigned to it. Manually changing it from <baselifestyle /> to <baselifestyle>Medium</baselifestyle> makes it work. It shouldn't be misbehaving like that though.

**Comment by HaikenEdge** [comment] 2015-09-27 14:59
I don't know what that means, but even if I try to buy a new lifestyle in Career mode, in which case I have to select a lifestyle there, I still can't buy months for this new lifestyle I bought, and it starts with 0 months.

**Comment by chummer5a** [comment] 2015-09-28 14:25
Should be fixed in dev, will be in 5.175.

**Closed** 2015-09-30 07:04 UTC
Labels: bug
