### ISSUE TITLE
Help Chummer Wiki link leads to old page with no information about this project

### ISSUE THREAD

**Issue by SquidPony** [chummer5a/chummer5a#715] opened 2016-02-25 07:04 UTC
### Expected behaviour
I would expect it to come to a page about the current version of the project, maybe just the git home page for it

### Actual behaviour
goes to the old chummer page

### Steps to reproduce the behaviour
ctrl-F1 or select it from the menu in app

**Comment by chummer5a** [comment] 2016-02-25 23:48
Mostly that's because we haven't pulled over all of the content from the original wiki, so the old wiki's more useful.

**Comment by SquadronROE** [comment] 2016-05-29 00:53
I think this makes sense, and we could close the bug as working as designed unless someone wants to start writing more documentation on the project.

**Comment by joha4270** [comment] 2016-06-30 08:20
While hella late, i'm agreeing with @SquadronROE and closing this until some poor soul decides to start writing documentation. I'll see if i can rope somebody into it before SR7....

**Closed by joha4270** 2016-06-30 08:20 UTC
