### ISSUE TITLE
Unable to create character using Priority or Sum-To-Ten

### ISSUE THREAD

**Issue by AbigRedBall** [chummer5a/chummer5a#951] opened 2016-06-21 17:47 UTC
Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.

### Chummer Version
5.181.0

### Expected behaviour
Creation of character.

### Actual behaviour
Program crashes repeatedly.

### Steps to reproduce the behaviour
Create new character using Priorty or Sum To Ten method. Program crashes after selecting next seemingly no matter what options are selected.

### Link to affected character file
No file generated.

**Comment by Dwarfknight** [comment] 2016-06-22 10:50
I have this same issue.

**Comment by chummer5a** [comment] 2016-06-22 12:09
Could you please try updating to the latest nightly build and see if it
still happens?>

**Comment by eeboaz** [comment] 2016-06-23 03:11
While not the originator, I was able to create a character using priority build using 5.181.30.

**Comment by Dwarfknight** [comment] 2016-06-24 01:48
Sorry it took awhile for me to respond. I updated to the nightly version and the issue is fixed now.

**Comment by AbigRedBall** [comment] 2016-06-25 05:09
Seems to work in nightly build now

**Comment by joha4270** [comment] 2016-06-25 08:27
Seeing that everybody agrees this is fixed, i'm going to close this issue. A bit late, but out of curiosity did you try and create a character without magic?

**Closed by joha4270** 2016-06-25 08:27 UTC

**Comment by Dwarfknight** [comment] 2016-06-25 11:53
>  did you try and create a character without magic?

yes
