### ISSUE TITLE
Lifestyle - garage

### ISSUE THREAD

**Issue by Malkleth** [chummer5a/chummer5a#444] opened 2015-10-11 01:17 UTC
It seems like the Garage and Cramped Garage share an index or something, because when trying to add one I get both.

**Comment by chummer5a** [comment] 2015-10-13 07:29
Hrm, I can't reproduce it. Does it happen for all of the garages?

**Comment by Malkleth** [comment] 2015-10-13 21:02
Aha! So it seems to be related to adjusting the point values first (eg: on
a medium lifestyle, increasing Security by +1) and then adding those
positive qualities.

So what I have that's reproducible:
1) add new medium lifestyle
2) add Garage (body 5 or more), save
3) edit again, adjust security to 4/4, save
4) garage quality (at least) goes into an error state. It seems to be
removed; if you add it again it shows up as Cramped Garage

**Comment by chummer5a** [comment] 2015-10-17 23:17
That's... an interesting bug. Hrm.

**Comment by chummer5a** [comment] 2016-01-12 07:41
Fixed in one of the recent commits.

**Closed by chummer5a** 2016-01-12 07:41 UTC
Labels: bug
