### ISSUE TITLE
Missing Powers

### ISSUE THREAD

**Issue by tealayene** [chummer5a/chummer5a#2556] opened 2018-03-03 22:41 UTC
Using Chummer Version 5.198.0 the critter powers that are listed in the Dark Terrors book are
missing such as Bacchanal, Dread Feast, Evolved Reflexes, and Morningstar Fall are just some of the
examples of what are missing.

**Comment by DelnarErsike** [comment] 2018-03-04 01:15
Closed this issue because it is a part/duplicate of #2106.

**Closed by DelnarErsike** 2018-03-04 01:15 UTC
Labels: bug: data file content, duplicate
