### ISSUE TITLE
Magic Value bug 0s out charsheet on load.

### ISSUE THREAD

**Issue by MandozerTheGreat** [chummer5a/chummer5a#309] opened 2015-07-26 09:17 UTC
Unhandled exception has occured yadda yadda.

Value of '11' is not valid for 'Value'. "Value" should be between "minimum and Maximum. Parameter Name: Value.
chummer file and logs below.
https://drive.google.com/file/d/0Bwu-ssbXNGYMZG9LaHNhWkVyMDg/view?usp=sharing

http://pastebin.com/xxLnLva2

**Comment by joha4270** [comment] 2015-07-26 09:46
Quite sure this is a duplicate of #300

**Closed by joha4270** 2015-07-26 09:46 UTC

**Comment by chummer5a** [comment] 2015-07-26 09:53
I still can't reproduce this. I've made characters that are an exact carbon
copy of bugged ones and I can't get it to do the 11 thing. Driving me up
the wall.
