### ISSUE TITLE
Wierd behaviour with spare ammo clips

### ISSUE THREAD

**Issue by Iberis** [chummer5a/chummer5a#1015] opened 2016-07-20 16:50 UTC
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.182.0
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Actual behaviour
I purchased 2 spare clips for a weapon. Then I took my total amount of ammunition and right click dragged it into the clips. This lead to the ammo being listed belonging to the clips, as an indication of the ammo being loaded into the clips.
When I went to purchase additional clips for different ammo types, it would not add any clips to my gear list, but it would subtract the cost of the clips multiplied by the cost of the total ammunition. Indicating that it thought I had that much ammo PER clip instead of total.
After a reload, chummer also halved all the ammo counts I had assigned to clips. I assume this happened because I loaded my guns, but this is inconsistent with the ammo per clip behaviour.

I also noted that when I reload my weapons, it will list the available sources as "Ammo: (Ammo Type) x(Total Ammo) Spare Clip @ (Gear Location)"
It will then remove a spare clip from the stack, without affecting the ammo assigned to it. This seems like desirable behaviour but again contradicts the "ammo per clip" behaviour.

### Expected behaviour
Chummer should not attempt to buy full clips if you use gear -> Spare clips -> and then select a weapon type you already own loaded clips for. There is already a way to do this by selecting the stack and clicking the '+' icon.

Further it should be confirmed whether or not the same behaviour for loaded clips is used universally. It appears only the issue of buying new clips assumes ammo per individual clip, and all other mechanics treat ammo as total ammo.

### Steps to reproduce the behaviour
For finished Characters: Buy ammo, Buy spare clip. Right click drag ammo into clip. Attempt to buy a new spare clip for the same weapon. Confirm that the money has been subtracted in the Karma and NuYen tab.
Further you can select the clip and see that it's value will be (amount of clips in stack) * (value of total ammo assigned to stack) + 5¥ per clip

### Link to affected character file
[Raven.zip](https://github.com/chummer5a/chummer5a/files/374218/Raven.zip)

**Comment by joha4270** [comment] 2016-08-15 17:01
What you have encountered is intended behavior. Child items for gear are counted as a "each item has" not "all items in total has". 

We have seen a few cases where this has caused issues (capsule rounds), but on the development team we still consider this the correct way to handle this. You are welcome to open a new ticket suggesting an alternative logic and your reasons for it, but better prepare to be convincing. 

Until then, i'm closing this as "Feature, not bug"

**Comment by Iberis** [comment] 2016-08-16 19:54
I don't care about your stacking. If I assign ammo to a clip, I CANT BUY MORE CLIPS

**Comment by chummer5a** [comment] 2016-08-18 00:31
Right, I see the problem. It works a bit differently in creation mode. Shouldn't be too hard to fix.

**Closed** 2016-08-20 16:54 UTC
