### ISSUE TITLE
Submersion Issues

### ISSUE THREAD

**Issue by SpiffierMage00** [chummer5a/chummer5a#4994] opened 2023-02-19 03:17 UTC
Submersion Rank 2 Issue
Whenever I try and buy Submersion Rank 2 for a Technomancer character, it adds the rank but does not increase the cap on resonance. Additionally any further purchase of submersion repeats the purchase of rank 2 and any attempt to delete any rank 2 submersion gives me a pop-up stating that the highest submersion must be deleted first.

To Reproduce
1. Purchase a Rank 2 Submersion as a Technomancer character
2. Observe Resonance
3. Attempt to increase or delete rank

Expected behavior
The Maximum Resonance on the character should increase, ranks higher than 2 should be available for purchase in ascending order and attempts to delete the rank should work.

**Comment by DelnarErsike** [comment] 2023-02-26 23:01
Duplicate of #4980. Fixed in the Nightlies already.

**Closed by DelnarErsike** 2023-02-26 23:01 UTC
