### ISSUE TITLE
Issue: - Adding points to Resonance provocated crash

### ISSUE THREAD

**Issue by Zeidra-Senester** [chummer5a/chummer5a#3143] opened 2018-10-23 14:28 UTC
### Environment
Crash ID: a3fe32f4-4a81-4b3d-8971-e61e38741633
Chummer Version: 5.202.71
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
Resonance would get more ability points

### Actual behaviour
Software Crashes

### Steps to reproduce the behaviour
Human Technomancer, , Cryptome Paragon, Technochaman Resonant Stream ; added 6 points to Logic, tried to add points to Resonance : leads to Crash.

**Comment by DelnarErsike** [comment] 2018-10-30 08:54
Could you perhaps upload a savefile of the affected character? I can't seem to replicate the crash with my own set.

**Comment by Zeidra-Senester** [comment] 2018-11-04 14:41
No, it was a test file and it crashed before I could save it.

**Comment by DelnarErsike** [comment] 2018-11-04 19:11
Since we can't replicate the crash using a savefile, I'm closing this issue for now. If you are able to get a savefile where you can reproduce this crash, feel free to re-open the issue and upload your character file so the crash can be fixed.

**Closed by DelnarErsike** 2018-11-04 19:11 UTC
Labels: bug: application error
