### ISSUE TITLE
Skills not displaying correctly

### ISSUE THREAD

**Issue by atma288** [chummer5a/chummer5a#1998] opened 2017-10-27 18:32 UTC
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.195.54
Environment: 7 enterprise
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
full active skill name should display; karma entry on skill tab is also abridged

### Actual behaviour
first ~5 or so characters aren't displaying

### Steps to reproduce the behaviour
click skill tab. attempted resolution: tried vertical monitor, landscape monitor; full screen/wide screen; uninstall/reinstall
![ouch](https://user-images.githubusercontent.com/33162484/32119569-a76544dc-bb23-11e7-829d-ebb27cad4589.png)

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment] 2017-10-30 22:58
This issue is reliably caused by increased text size/DPI settings on Windows 7 only. Duplicate of #1900

**Closed by chummer5a** 2017-10-30 22:58 UTC
Labels: bug: application error
