### ISSUE TITLE
Improved Reflexes + Qi Focus gives erroneous +1 REA

### ISSUE THREAD

**Issue by exurgent** [chummer5a/chummer5a#3022] opened 2018-09-19 13:10 UTC
(present both in Release 5.202 and Nightly 5.202.40)

**To Reproduce**
1. Create new character, all default settings
2. Add Adept quality and MAG Rating >= 2
3. Add adept power Improved Reflexes, rating 1
&rarr; Reaction is 1(2), as it should be
4. Buy a rating 4 Qi Focus
5. Check the box under "Bound Foci" and select Improved Reflexes in the popup 
&rarr; Recation now reads as 1(4), the balloon tip lists  _REA (1) **+ (1)** + Improved Reflexes (2)_
6. Unbind the focus and bind it again, again selecting Improved Reflexes
&rarr; Reaction still reads as 1(4), however the balloon tip now lists  _REA (1) **+ (1) + (1)** + Improved Reflexes (2)_

That phantom (1) clearly shouldn't be there. Side note: If you do the same with an R8 focus (holding two levels of Improved Reflexes) or two R4 foci (holding one level each) the result is still just a +1 to REA

**Comment by chummer5a** [comment] 2018-09-19 13:40
It's a bug with how Qi foci work currently (obviously), I'm looking into it. Not really a good workaround for it at present, aside from making qi foci just grant additional power points, but that makes weird things happen.

**Comment by chummer5a** [comment] 2018-10-02 11:27
Duplicate of #2987

**Closed by chummer5a** 2018-10-02 11:27 UTC
Labels: bug: application error
