### ISSUE TITLE
Feature Request: Remove all Config-Items from Windows Registry

### ISSUE THREAD

**Issue by Nedorus** [chummer5a/chummer5a#3858] opened 2019-09-10 09:18 UTC
**Is your feature request related to a problem? Please describe.**
In case of using a shared installation (e.g. running Chummer from a Google Drive) options changes often need to be made across multiple machines because many option items (e.g. the enabled books) are stored in the windows registry.
This also makes it difficult to share a common settings file for the entire player group. Even when sharing the settings file, each player has to manually change stuff in the settings.
This becomes particularly annoying when playing several groups which use different options / books etc.

**Describe the solution you'd like**
All options should be moved to the settings file, no information should be written into the windows registry as that makes settings non-portable.

**Describe alternatives you've considered**
Maybe it could make sense to have options for UI / Paths and "gameplay relevant" options in separate files so that everything gameplay relevant can be shared across the group while each player can have individual UI settings.

**Additional context**
![image](https://user-images.githubusercontent.com/25143888/64601048-7c0c3d00-d3bc-11e9-8199-a8da13579802.png)

**Comment by chummer5a** [comment] 2019-09-10 23:19
Duplicate of #3532, effectively. Data is currently considered global because books are loaded as global static references. Changing it to per-character will either blow out memory usage for each character that's loaded, or require that we stop caching books entirely, which will have performance impacts. 

Either way, I'm looking into it, it's just a pain.

**Closed by chummer5a** 2019-09-10 23:19 UTC
