### ISSUE TITLE
Skill groups (Carreer: Skill points added broken group skill lost at load, Creation: adding points to broken group moved to karma at load)

### ISSUE THREAD

**Issue by graptis** [chummer5a/chummer5a#776] opened 2016-03-25 17:40 UTC
### Chummer Version
5.179

### Expected behaviour
1) Skill points that are increased beyond the group to be normally calculated after reload
2) If the "allow break skill groups in character creation" optional and "use skill points on broken groups" house rules are selected, allow any combination of skill points/karma to skills of broken groups

### Actual behaviour
1) In career mode, any skill points added to a skill after breaking its group are lost when loading the character
2) Skill points added to a broken group are turned to karma point expenditure if the character is saved/loaded

### Steps to reproduce the behaviour
1) Create a character with a priority allowing skill groups (C). Spend points as normal, add **Acting** group **2**, and move to career mode. Add karma reward. Increase the **Con** to **3**. Save character. Load. **Con** is now back to 2 and the karma is lost.
2) Enable "break groups on creation" optional rule and "use skill points on broken groups" house rule. Create character with skill priority (B). Spend 2 points on **Acting**. Break **Acting** group. Add a skill point (not karma) to **Con**. Save character. Load. **Con** now has **1** karma points spent and only the **2** skill points from the group, and the character has the additional skill point to spend.

##Helpful Fields
These may not be relevant in most cases. If they are, please fill them out. Otherwise, feel free to remove them.

### Link to affected character file

**Comment by graptis** [comment] 2016-03-25 17:41
I am quite happy to try and tackle this issue on my own and submit a pull when I'm done. Going through the code though I was unsure about two parts: 
This bit of code seems to be part of the issue, but I am not sure what it is fixing. Does anyone remember its intent so I can try and work around it?
(Character: Load())
		// Apply the broken skill group fix
		foreach (Skill objSkill in _lstSkills)
            {
                foreach (SkillGroup objGroup in _lstSkillGroups)
                {
                    if (objGroup.Broken && objGroup.Name == objSkill.SkillGroup)
                    {
                        objSkill.FreeLevels = objGroup.Rating;
                        objSkill.Base = objGroup.Rating;
                        objSkill.Karma = objSkill.Rating - objSkill.Base;
                    }
                }
            }

Second, from what I saw it would be "rather easy" to fix the career mode part if all skillpoints were forced to be saved as "base" part on the skill (as opposed to having it split between the "base" and the "karma" parts as is necessary on character creation). Is that all right to do or is the information of what was increased as skill points and what was increased as karma necessary when the character is on career?

**Comment by joha4270** [comment] 2016-03-25 17:43
As far as i can see this is a duplicate of  #428 

Also the entire skill system is actively being rewritten on the branch newskills (that is acctually reason we haven't released the next update but there keeps being more work)

**Closed by joha4270** 2016-03-25 17:43 UTC
