### ISSUE TITLE
Issue with skill points being assigned automatically during creation when only karma is used to level them.

### ISSUE THREAD

**Issue by Pacmanyo** [chummer5a/chummer5a#251] opened 2015-06-27 09:53 UTC
Using priority order creation type.

When you add skills with karma only and save it during initial character creation, the sheet will add the equivalent amount of skill points to match the rating by trying and using free skill points, even if character doesn't have any left, throwing both your skill points and your karma total off.

**Comment by joha4270** [comment] 2015-06-27 17:47
Issue a duplicate of #241, that is fixed in 1.568

If you believe you have found another issue, please reopen this issue.

**Closed** 2015-06-30 11:03 UTC
