### ISSUE TITLE
Toxins added to capsule rounds price not adjusted

### ISSUE THREAD

**Issue by mccrapshot** [chummer5a/chummer5a#1568] opened 2017-04-08 01:04 UTC
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.192.8.0
Environment: Wihndows 7 x64 and Windows 10 x64
Runtime: 4.6.2

### Expected behaviour
When adding drugs or toxins to capsule rounds, 1 drug should be enough for 5 capsule rounds. Therefore, the cost of adding a drug or toxin to a stack of capsule rounds should be (Toxin Cost)*[(Number of Capsule Rounds)/5 rounded up to nearest whole number]

### Actual behaviour
Cost is just (Toxin Cost)*(Number of Capsule Rounds) which is 5X more expensive than it should be

### Steps to reproduce the behaviour
Add toxins as plugins to capsule rounds

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment] 2017-04-08 06:38
Duplicate of #773. Current code doesn't care about dilution, so it's just a 1:1 relationship between child items and the counts. New ammo system will account for it differently by allowing you to fill the capsules with a nominated thing, so it'd keep everything in track properly.

**Closed by chummer5a** 2017-04-08 06:38 UTC
