### ISSUE TITLE
Enchanter cannot add Preparations

### ISSUE THREAD

**Issue by guildsbounty** [chummer5a/chummer5a#1962] opened 2017-10-15 02:25 UTC
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.195.41
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
Enchanter should be able to add preparations for Alchemy

### Actual behaviour
Enchanter cannot add 'spells' of any sort

### Steps to reproduce the behaviour
Create a new character with the Enchanter positive quality
Go to 'Spells and Spirits' tab and click Add Spell
Nothing happens.

**Comment by DelnarErsike** [comment] 2017-10-15 12:25
Unable to reproduce in my dev build. I can easily add spells to an Enchanter character, have them show up in the spells list, have them saved with the character, and have the printed out on the character's sheet.

I'm closing this for now. If you cannot add spells in the next Nightly version, please re-open.

**Closed by DelnarErsike** 2017-10-15 12:25 UTC
Labels: bug: application error, bug: data file content
