### ISSUE TITLE
Critter Attributes showing incorrectly

### ISSUE THREAD

**Issue by Mliekseter** [chummer5a/chummer5a#2052] opened 2017-11-14 20:32 UTC
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.195.0
Environment: Windows 10
Runtime: Don't know

### Expected behaviour
When creating a critter, it starts with attributes according to its metatype minimums/maximums

### Actual behaviour
When creating a critter, all its non-Special attributes are reduced by 3, often displaying as zero. Attribute minimums/maximums are also reduced by this amount. Special attributes are the same, but only reduced by 1. Magic displays correctly on at least some Critters

### Steps to reproduce the behaviour
Open Chummer
File > New Critter
Default Settings
Select a Critter (I have tested with Eastern Dragon, Domestic Cat, Bastet (Dosmetic Cat), Juggernaut, & Bandit)
Note the Attribute Minimums/Maximums shown on the metatype selection window. At this point they are correct
Press Ok
Note the Attribute Values, Minimums & Maximums shown on the Attributes tab. They are now incorrect

### Link to affected character file
(Enter text here)

![critter01](https://user-images.githubusercontent.com/33670250/32803247-d31a7768-c97a-11e7-8ad7-d86c26fac68d.PNG)
![critter02](https://user-images.githubusercontent.com/33670250/32803253-d727a3da-c97a-11e7-86d3-58b172924163.PNG)

**Comment by Mliekseter** [comment] 2017-11-14 20:36
Looking at the Critters.xml file, I think the cases where Magic displays properly are where the critter has a value included with the <enableattribute> stuff
ie, 
<enableattribute>
  <name>MAG</name>
  <min>1</min>
  <max>7</max>
  <aug>7</aug>
  <val>4</val>
</enableattribute>

**Comment by Mliekseter** [comment] 2017-11-14 22:08
Looking at my own screenshots above, I realise that the reduction isn't always by 3, since in the ones above the attributes have been reduced by 1. Domestic cats and Juggernauts do show the 3 point reduction however;
![critter03](https://user-images.githubusercontent.com/33670250/32807606-4f07a79e-c988-11e7-8af1-79a51372380e.PNG)
![critter04](https://user-images.githubusercontent.com/33670250/32807611-521cb97e-c988-11e7-8b21-d266d7cf85ac.PNG)

**Comment by chummer5a** [comment] 2017-11-14 22:37
From memory this is fixed in current nightly builds, there was a bit of holdover logic from 4E where their attributes were reduced for some reason.

**Comment by chummer5a** [comment] 2017-11-17 14:14
Can't reproduce in current nightly builds.

**Closed by chummer5a** 2017-11-17 14:14 UTC
Labels: bug: application error
