### ISSUE TITLE
skills tab not usable

### ISSUE THREAD

**Issue by falcron** [chummer5a/chummer5a#2270] opened 2018-01-07 20:41 UTC
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.195
Environment: Windows 7 pro

### Expected behaviour
able to view skills in skill tab

### Actual behaviour
After character finalized the skills tab is scrunched and not usable.
 
### Steps to reproduce the behaviour
Opened Chummer with existing character and selected the Skills tab.

### Link to affected character file
(Enter text here)
![capture-1](https://user-images.githubusercontent.com/35201701/34653875-4f8a7be0-f3b0-11e7-8df4-d846400cc36a.JPG)

**Comment by chummer5a** [comment] 2018-01-07 21:16
The skills tab doesn't currently play nice with resized text controls in Windows 7. Duplicate of #1900

**Closed by chummer5a** 2018-01-07 21:16 UTC
