### ISSUE TITLE
Limit modifications from Adept Powers and Qualities do not persist after Save/Load during Creation.

### ISSUE THREAD

**Issue by W1ld3b34st** [chummer5a/chummer5a#212] opened 2015-05-18 19:32 UTC
This cannot be reproduced after a character has entered the "Created" state. 

When selecting the "Improved Potential" Adept Power or "Indomitable" Quality for any limit, it will appear to be correctly set. When you either save the character and reload it, or mark it as created and save it, upon reload the modified limit will return to the default value.

This does not happen when either purchasing the Adept Powers or Qualities post-creation.

**Comment by joha4270** [comment] 2015-05-19 08:33
Adept part US duplicate of #146

**Comment by joha4270** [comment] 2015-05-19 09:02
Unable to reproduce by following the following steps

Create new character -> Add adept quality -> Add power (Improved Potential(mental)) -> save sheet -> close chummer -> open chummer -> Mental limit is the right value from power and attributes -> mark as created -> Mental limit not changed

**Comment by W1ld3b34st** [comment] 2015-05-19 16:19
Apologies for not including specific reproduction steps for the initial report. Also appears the Adept Power does get saved. The Indomitable Quality however does not appear to work. To be clear I was incorrect in the Improved Potential having an issue.

Reproduction for the Indomitable Quality is as follows

Create New Character -> Select Priority Build with Normal level, do not ignore creation rules -> Select any settings from this menu -> Check Limit values once modifying character -> Select Indomitable Quality (Testing with Mental/Physical, assuming it also works for Social) -> Check Limits they should have updated correctly -> Save the character -> Reload the character -> Check limits, they will have reverted

**Comment by joha4270** [comment] 2015-05-19 16:22
Thanks for more specific instructions. I'm going to be occupied for the next 15 hours but after that i'm going to take a look at it.

**Comment by chummer5a** [comment] 2015-05-20 14:32
Missing Improvement types in ClsImprovement. Also an atrociously wrong interpretation of how Indomitable works. Resolved in 5.167.

**Closed by chummer5a** 2015-05-20 14:32 UTC
