### ISSUE TITLE
Dikote, Weapon Foci, and Turn options

### ISSUE THREAD

**Issue by IkariMadness** [chummer5a/chummer5a#3431] opened 2019-02-12 02:38 UTC
For the first two suggestions, would be additions to the actual item listing.  Could it be possible to add Dikote as a weapon accessory for melee weapons that would adjust the AP and Damage accordingly.

The Weapon Focus issue that I have encountered is that on the Street Gear, weapon page, when selecting a melee weapon that serves as a foci, the dice pool is not augmented by the Foci strength.  Only showing dice pool according to skill/attribute.

The final suggestion, would be when firing a weapon from the street gear page, list each firing mode as a simple / complex action and maybe even add a window or pop up prompt that would inform the player of the defense modifier for that firing mode.  For example.  If a weapon has BF / FA capabilities, if the player hovers over '10 round full auto' selection, they would see an info box that shows "Complex Action, -9 defense."

Thank you for your attention and any feedback.

**Comment by chummer5a** [comment] 2019-02-12 03:09
Dikote's not in any of the books. You can make your own accessory using the [custom data files](https://github.com/chummer5a/chummer5a/wiki/Custom-Data-Files).

The focus thing is a duplicate of #3320 and #1848.

There's some backend stuff that's been done for listing actions, but it's at a bit of a back seat while I implement other stuff.

**Closed** 2019-12-26 14:09 UTC
Labels: feature
