### ISSUE TITLE
Item request: Hand load ammo option

### ISSUE THREAD

**Issue by Morcleon** [chummer5a/chummer5a#1564] opened 2017-04-05 04:01 UTC
Hard Targets pg 189 has an ammo modification that increases DV or AP of your bullets by 1 for an extra +10% cost (and an Armorer check if you make them) or a +25% cost (if you have someone else make them for you).

Any way we can get this as an option when we're adding in ammo? Maybe as one pair of checkboxes for self-crafted/bought, and one pair of checkboxes for DV/AP, underneath the dropdown box for selecting the type of weapon the ammo is for?

**Comment by chummer5a** [comment] 2017-04-05 05:18
Duplicate of #759. It'd be messy to implement with the current system, as everything's basically bolted onto the gear class. Plan is to make ammo into a separate equipment extension class that can support the weird things like capsule rounds without further compromising how the gear class functions.

**Closed by chummer5a** 2017-04-05 05:18 UTC
Labels: duplicate
