### ISSUE TITLE
Bug: Lifestyle Tab is Blank

### ISSUE THREAD

**Issue by truchert-orange** [chummer5a/chummer5a#3059] opened 2018-09-28 19:17 UTC
**Describe the bug**
On all characters, new and existing, on 5.202.50 have no content on the Street Gear -> Lifestyle tab. There is no visible way to add or manage lifestyles.

**To Reproduce**
1. Install Chummer 5a 5.202.50
2. Create a new character using Priority Selection with any priority distribution
3. Click on Street Gear tab
4. Click on Lifestyle tab
5. Note that the tab is blank

**Expected behavior**
Clicking on the lifestyle tab should show the available lifestyle options and allow you to configure, add, and remove lifestyles for the selected character.

**Screenshots**
![no lifestyle](https://user-images.githubusercontent.com/25309761/46228743-efd24880-c317-11e8-83ca-dde1ad661efe.PNG)

**Character File**
[Ray.txt](https://github.com/chummer5a/chummer5a/files/2429428/Ray.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Version 5.202.50

**Additional context**
This only occurred on this most recent update, to my knowledge.

**Comment by DelnarErsike** [comment] 2018-09-29 11:51
Duplicate of #3057

**Closed by DelnarErsike** 2018-09-29 11:51 UTC
