### ISSUE TITLE
Refresh times on existing characters

### ISSUE THREAD

**Issue by OLStefan** [chummer5a/chummer5a#1934] opened 2017-10-01 14:03 UTC
From the Chummer Thread on the german Pegasus forums.

### Environment
Chummer Version: Since 5.193.0

### Expected behaviour
Not having the time chummer is running effect performance.

### Actual behaviour
After having chummer open for a while selecting gear/weapons/ware/etc on your character takes very long until chummer is workable again. Sometimes it completely freezes.

### Steps to reproduce the behaviour
1. Load on the the provided characters
2. Click through the character for about a minunte
3. Select e.g. one of the character's weapons

### Link to affected character file
https://www.dropbox.com/s/ilgsgwzqc0dmqc2/SamSpiel.chum5?dl=0
https://www.dropbox.com/s/gxhp23ay7qsjkg6/SparkySpiel.chum5?dl=0

**Comment by cuckooman** [comment] 2017-10-26 13:27
Can confirm, happens even on i7 3770K.

**Comment by MerGatto** [comment] 2017-10-28 20:08
Could reproduce the issue with several characters and noticed that the freezing only starts after opening the skill tab

**Comment by DelnarErsike** [comment] 2017-11-04 02:01
This issue seems to be caused by multiple sources, and I think most of them have been caught and fixed in the nightly build by now (though nightly may still have its own, unrelated bugs). The main sources of the issue seemed to be either unnecessary calls to refresh the active skill section (e.g. in many cases, simply changing the cyberware that you had selected was enough to trigger a refresh) or unnecessary extra work performed at every refresh of active skills (e.g. according to Joha, at one point, skills refreshes in career mode would redraw the calendar about 100 times per refresh).

See if you can still get these freezes when using the current nightly.

**Comment by MerGatto** [comment] 2017-11-07 10:15
Tested it with several characters now and it seems to be fixed

**Closed** 2017-11-07 11:25 UTC
Labels: bug: application error, response pending
