### ISSUE TITLE
Capsule rounds + Toxins cost math is adding an extra zero the end of the cost of toxins

### ISSUE THREAD

**Issue by Geose404** [chummer5a/chummer5a#2290] opened 2018-01-12 03:32 UTC
### Environment
Chummer Version: 5.196.0
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
During Character Creation
Under Street Gear
  Under Gear
    Capsule rounds cost 5 NewYen per ten Rounds
     Add as plug in Add 2 doses of Neuro-Stun 60Y each so 120Y total
Total pakage should cost 125Y
### Actual behaviour
The math calculating the price seems to be
Main line item                                            5Y
First plugin Cost x Quantity 60x2       +120_Y
                                                             1205Y
Adding additional toxins like DSMO adds to the price as above, with an extra zero in the prive
### Steps to reproduce the behaviour
Use "add as plugin" Toxins to capsule rounds while in Character creation
![image](https://user-images.githubusercontent.com/8345223/34858591-e00ae68c-f716-11e7-839f-b94bf8034dbb.png)
![image](https://user-images.githubusercontent.com/8345223/34858593-e4c1576a-f716-11e7-8056-abefd9601e28.png)
![image](https://user-images.githubusercontent.com/8345223/34858599-e9fa723e-f716-11e7-9e19-05971773df5e.png)

**Comment by chummer5a** [comment] 2018-01-12 03:33
Known issue, duplicate of #773

**Closed by chummer5a** 2018-01-12 03:33 UTC
