### ISSUE TITLE
Impossible to  create player

### ISSUE THREAD

**Issue by Dedalios** [chummer5a/chummer5a#2405] opened 2018-01-27 01:59 UTC
## Environment
Chummer Version:Nightly-v5.197.14
Environment: windows10
Runtime: (If you don't know this, it is probably .NET 4.5.1)
 
Métatype not exist

**Comment by chummer5a** [comment] 2018-01-27 07:07
Duplicate of #2406?

**Closed by chummer5a** 2018-01-27 07:07 UTC

**Comment by Dedalios** [comment] 2018-01-27 10:58
the bug software to create this report and I assumed that the information in the report had been transmitted. We start the software, we get the starting page. we ask the creation of the character, and no more metatype anything impossible to create the character.
