### ISSUE TITLE
Implementing Hand-loading

### ISSUE THREAD

**Issue by MaraFaye** [chummer5a/chummer5a#2586] opened 2018-03-11 17:48 UTC
### Environment
Chummer Version: 5.198.29
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

Since Hard Targets there is an option for hand-loading your ammo at 110% of the standard price to add either a +1 to DV or -1 to AP (not both).
I know you could just buy the ammo at 110% price and but a note on it that it's hand-loaded, but could there be a not overly complicated way to "officially" mark ammo as hand loads?

**Comment by joha4270** [comment] 2018-03-11 18:05
Duplicate of #759

To make a long story short, because how Chummer is made, getting handloads to work in a sane way is hard.

**Closed by joha4270** 2018-03-11 18:05 UTC

**Comment by MaraFaye** [comment] 2018-03-11 21:45
Guess the sanest method then is just using notes to seperate the ammo if necessary and using the markup function for the cost.

**Comment by chummer5a** [comment] 2018-03-12 01:57
One option might be to create custom files that include the DV or AP bonus and the increased cost; I just don't want to do that as our main implementation, as it'll bloat the ammo category.

**Comment by MaraFaye** [comment] 2018-03-13 15:25
Would be adding it as a plugin to the ammo an option? Like Licenses on SINs. That way you could just create 2 entries and use them for all ammo types. (I actually don't know anything about programming so I might come up with ideas that sounds simple but aren't when in code.)

**Comment by chummer5a** [comment] 2018-03-14 02:50
Not really; the UI element of it is borderline irrelevant. The problem is that we'd have to rewrite the ammo bonus from gear anyway to support picking up bonuses from child items, so for the effort involved I'd prefer to just calve it off into a separate sub class specifically for ammunition. This would allow me to also implement stuff like injection rounds 'properly' without contaminating the rest of the gear class with weird edge cases.
