### ISSUE TITLE
WIndows Defender Trojan:Win32/Bitrep.A detected on Textblock Converter.exe

### ISSUE THREAD

**Issue by killraven76** [chummer5a/chummer5a#1911] opened 2017-09-23 15:54 UTC
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.195.0
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
No malware detected

### Actual behaviour
Windows defender quarantined Textblokc Converter.exe detected as Trojan:Win32/Bitrep.A

### Steps to reproduce the behaviour
Unquarantine the file and rescan

### Link to affected character file
[Textblock Converter.zip](https://github.com/chummer5a/chummer5a/files/1326642/Textblock.Converter.zip)

**Comment by DelnarErsike** [comment] 2017-09-25 13:02
Unable to reproduce, and the linked file is not identical to the executable found in the latest release version, nor to the one found in the latest nightly version. You either got a false positive on Windows Defender, or a piece of malware injected itself into your executable.

I will be closing this for now.

**Closed by DelnarErsike** 2017-09-25 13:02 UTC
