### ISSUE TITLE
Saving changes to global options

### ISSUE THREAD

**Issue by nghtwlkr** [chummer5a/chummer5a#4342] opened 2021-03-19 22:03 UTC
### Environment
Crash ID: 69e0014f-9048-4501-ba57-ffb0466c4a67
Chummer Version: 5.214.6
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000
Option upload logs set: NotSet
Installation ID: 40349b0d-2b5a-4611-9562-679ab97bae7c

### Expected behaviour
(Enter text here)

### Actual behaviour
(Enter text here)

### Steps to reproduce the behaviour
(Enter text here)

**Comment by DelnarErsike** [comment] 2021-03-20 11:58
Cannot reproduce. Can you tell me what exact changes you were trying to save?

**Comment by nghtwlkr** [comment] 2021-03-20 15:20
Actually it was any change. It didn't matter. I suspect it had to do with
trying to link the pdf files to the program so that theonks would work
becuase they seemed to be the only thing that didn't actually save when the
program reloaded. After I went back to a stable build instead of a nightly
build the problem stopped

**Comment by DelnarErsike** [comment] 2021-03-21 04:01
Well, that's the whole point of the Nightly. If you're getting a bug with the Nightlies and I can't find a way to reproduce it and therefore fix it, guess what's going to pop up in the next stable build...

**Comment by Tom-0169** [comment] 2021-03-29 12:55
Happening in installation too.
Chummer has no internet access.
Upon saving ANYTHING in the options dialog the program crashes.

Crashhandler DOES have internet access, but crashes upon upload...

### Environment
Crash ID: 4bbec9ee-b616-4d7e-8732-71bdab5463d1
Chummer Version: 5.214.16
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000
Option upload logs set: Trace
Installation ID: 976f5326-50b1-411d-8e5c-d6cdace341d3

![2021-03-29 14_54_03-Global Options](https://user-images.githubusercontent.com/10605630/112839689-c2101b00-909e-11eb-9d33-bdc22a753a6c.png)
![2021-03-29 14_52_38-Crash_Crashhandler](https://user-images.githubusercontent.com/10605630/112839701-c50b0b80-909e-11eb-9a5b-af7d8344fab4.png)

**Comment by ArchonMegalon** [comment] 2021-04-13 18:32
I just checked in Application Inisghts and couldn't find the logs for this Installation Id. That is perfectly normal, because we still get flooded with logs and truncate at a certain amount each day. If that problem still persists in the latest nightly, please trigger it again (and hopefully, it will not be truncated again).

**Closed** 2021-07-18 10:03 UTC
Labels: bug: application error, response pending
