### ISSUE TITLE
Bug: Friends in High Places Does Not Ignore 7 Karma Per Contact Restriction

### ISSUE THREAD

**Issue by FableWright** [chummer5a/chummer5a#2216] opened 2017-12-27 17:19 UTC
### Environment
Chummer Version: 5.196.0
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Characters who count for Friends in High Places (Connection 8+) may have more than 7 karma spent on them. (And ONLY the contacts who count for Friends in High Places are given this exemption,)

### Actual behaviour
Character is invalid to move to career mode because contacts gained from Friends In High Places are worth more than 7 karma.

### Steps to reproduce the behaviour
1. Create a character with Friends in High Places and Charisma 3+
2. Create a contact with Connection 8/Loyalty 1
3. Observe that character cannot move to create mode due to their minimum-9-karma contact, though the separate pools for normal/FiHP contacts are working fine.
3a. Observe that there is no option to disable this restriction (nor allow higher-than-alpha-grade cyberware for Cybersnob, but that's a closed issue).

### Link to affected character file
[ShapeshifterFace.txt](https://github.com/chummer5a/chummer5a/files/1589516/ShapeshifterFace.txt)

**Comment by DelnarErsike** [comment] 2017-12-27 17:49
From what I can tell, this is a duplicate of #2171, which was fixed a few weeks ago in the latest nightly. I'm closing this issue, but if this isn't a duplicate, please re-open it.

**Closed by DelnarErsike** 2017-12-27 17:49 UTC
