### ISSUE TITLE
Okay, may fault... Eye Mounts again

### ISSUE THREAD

**Issue by Paperknight86** [chummer5a/chummer5a#4783] opened 2022-04-25 11:48 UTC
There's no possibility to build a cybereye into the mount. why?

**Comment by Paperknight86** [comment] 2022-04-25 11:51
Do cyber eyes still cost essence in a mount?

**Comment by DelnarErsike** [comment] 2022-04-28 22:06
Duplicate of #4193.

**Closed by DelnarErsike** 2022-04-28 22:06 UTC
