### ISSUE TITLE
Magic Initiate Level/Grade not editable

### ISSUE THREAD

**Issue by Klaive** [chummer5a/chummer5a#2524] opened 2018-02-25 03:35 UTC
### Environment
Chummer Version: 5.198.0.0
Environment: Windows 10
Runtime: .NET 4.5.1

### Expected behaviour
Once an Initiate grade is added it can't be deleted or modified through the improvements panel.

### Actual behaviour
None exists at this time

### Steps to reproduce the behaviour
N/A

### Link to affected character file
N/A

**Comment by chummer5a** [comment] 2018-02-25 12:40
Can't reproduce this in current nightly builds; please test with https://github.com/chummer5a/chummer5a/releases/tag/Nightly-v5.198.15

**Comment by Zitchas** [comment] 2018-02-25 14:54
Chummer 5.198.8

I just created two characters (one who initiated during character creation, and one who did not). Once they are advanced into career mode and the "improvements" panel is activated, I can't see "initiation" as an option in the pull down menu under either "add" or "edit" dialogue boxes for either character. This is my interpretation of what Klaive is saying, anyway.

I also checked in the regular Initiation panel, and both characters can add initiatory levels as normal, but cannot remove an initiatory grade. Is this normal (I don't know if it is even possible to lose an initiatory level)

Is this as intended? Improvements are generally speaking intended for editing stuff due to ingame events and/or GM fiat, right? I've seen GMs grant initiation as a reward for particularly harrowing astral encounters. I've never seen one removed, though.

**Closed** 2018-02-26 10:56 UTC
Labels: response pending
