### ISSUE TITLE
Crashes on opening Character after new update.

### ISSUE THREAD

**Issue by Demonicfox2000** [chummer5a/chummer5a#2267] opened 2018-01-06 19:09 UTC
### Environment
Chummer Version: 5.196.0
Environment: Windows 10
Runtime:  .NET 4.5.1

### Expected behaviour
To open the character Sheet inside of Chummer.

### Actual behaviour
Crashes before opening character

Error Report:

Faulting application name: Chummer5.exe, version: 5.196.0.0, time stamp: 0x5a2e16f3
Faulting module name: KERNELBASE.dll, version: 10.0.16299.15, time stamp: 0x2cd1ce3d
Exception code: 0xe0434352
Fault offset: 0x001008b2
Faulting process id: 0x39cc
Faulting application start time: 0x01d38720e3332767
Faulting application path: C:\Users\Justin\Desktop\Shadowrun Tabletop\Chummer\Chummer5.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 179a136f-df55-4d30-a488-0fdc00b9e986
Faulting package full name: 
Faulting package-relative application ID: 

### Steps to reproduce the behaviour
Opening Character in Chummer

### Link to affected character file
[Goldeneye.zip](https://github.com/chummer5a/chummer5a/files/1609114/Goldeneye.zip)

**Comment by Demonicfox2000** [comment] 2018-01-06 19:11
.NET Runtime Error:

Application: Chummer5.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.ThrowHelper.ThrowArgumentException(System.ExceptionResource)
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Insert(System.__Canon, System.__Canon, Boolean)
   at Chummer.Skills.SkillsSection.Load(System.Xml.XmlNode, Boolean)
   at Chummer.Character.Load()
   at Chummer.frmMain.LoadCharacter(System.String, System.String, Boolean, Boolean)
   at Chummer.frmCharacterRoster.treCharacterList_DoubleClick(System.Object, System.EventArgs)
   at System.Windows.Forms.Control.OnDoubleClick(System.EventArgs)
   at System.Windows.Forms.TreeView.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.OnMessage(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr, Int32, IntPtr, IntPtr)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application.Run(System.Windows.Forms.Form)
   at Chummer.Program.Main()

**Comment by DelnarErsike** [comment] 2018-01-06 20:58
Ah, yes, the "duplicate entries of the same skill" bug, caused by the way older code handled Magic- and Resonance-linked skills. AFAIK, the issue has been fixed in the Nightly, please re-open the issue if it isn't.

**Closed by DelnarErsike** 2018-01-06 20:58 UTC
