### ISSUE TITLE
Crash on saving while creating a critter V5.221.0-V5.222.0

### ISSUE THREAD

**Issue by Adventuredudes** [chummer5a/chummer5a#4755] opened 2022-03-25 02:19 UTC
The program crashes, producing a report, upon attempting to save a created critter, or during creating a critter

Steps to reproduce the behaviour:
1. create a critter
2. select any of the generation methods
3. attempt to save
4. program crash with error log

![error report](https://user-images.githubusercontent.com/102337995/160041506-2f71bda1-276c-4b45-b5ef-9098bc74bcc0.PNG)

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

 - OS: [e.g. Windows 10]
 - tested on Version [ 5.222.0 and 5.221.0 ]

Also attempted a clean install of the program with identical issues
Attempted to save with multiple kinds of critters, barghests, hellhounds and every kind of spirit and dragon

**Comment by chummer5a** [comment] 2022-03-28 01:01
Issue is caused by a bug when creating natural weapons. Has been resolved in nightlies.

**Closed by chummer5a** 2022-03-28 01:01 UTC
