### ISSUE TITLE
5.225.307

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#5100] opened 2024-01-14 20:39 UTC
Post gen you can't seem to add underbarrel weapons anymore. Pops us the you must select a weapon to add an accessory to window even if a gun is selected.

Tested with 5.225.307

**Comment by bulldogc** [comment] 2024-01-19 01:53
Also just realized I entered the summary stupid... Sorry.

**Comment by DelnarErsike** [comment] 2024-02-26 01:46
Duplicate of #5014, closing this issue.

**Closed by DelnarErsike** 2024-02-26 01:46 UTC
