### ISSUE TITLE
Toxin related ammo types (DMSO packs & capsule rounds)

### ISSUE THREAD

**Issue by MaraFaye** [chummer5a/chummer5a#2581] opened 2018-03-10 17:00 UTC
### Environment
Chummer Version: 5.198.27
Environment: Windows 7
Runtime: 4.7.1

### Expected behaviour
DMSO Gelpacks are the ammo type for the Ares Super Squirt, costing 20 per 10 rounds with an availability of 2R.

Capsule rounds need the prices for inserted toxins divided by 5 and then multiplied by 2 and then multiplied by the tens of rounds. The system being that 1 dose of a toxing fills 5 rounds, but you buy rounds in 10s.

### Actual behaviour
DMSO-Gelpacks are missing entirely from the ammo list (They are not the same as the drug DMSO).
The toxin prices for capsule rounds are simply multiplied by the amount of rounds, this calculation would be correct for the DMSO-Gelpacks and the injection darts, but doesn't apply to the capsule rounds.

### Steps to reproduce the behaviour
For DMSO-Gelpacks, look at the ammo list in the gear menu.
For the capsule rounds, add some and then some toxin, like Pepper Punch, instead of the price being 15 (5 for 10 rounds and 10 for 2 doses of Pepper Punch filling these 10 rounds) the price is 55, so one dose per round.

**Comment by chummer5a** [comment] 2018-03-24 06:55
Duplicate of #773

**Closed by chummer5a** 2018-03-24 06:55 UTC
Labels: bug: application error
