### ISSUE TITLE
Adding sprites as a technomancer crashes chummer 

### ISSUE THREAD

**Issue by roboticbomber** [chummer5a/chummer5a#2258] opened 2018-01-05 08:00 UTC
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.196.32
Environment: W7 Home Premiun
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
I'm assuming it'd let you actually make a sprite. I'm not sure, because this is my first technomancer.

### Actual behaviour
Chummer softlocks as the menu to create a sprite opens, meaning you'll have to force quit Chummer.

### Steps to reproduce the behaviour
As a technomancer under "Complex Forms and Sprites" click "Add Sprite" at the bottom and the application will crash. 

### Link to affected character file
https://www.dropbox.com/s/z5cg3nr1acobw2k/Unnamed%20Technomancer%20-%20Copy.chum5?dl=0

**Comment by DelnarErsike** [comment] 2018-01-05 16:50
From what I can tell, this is a duplicate of #2254, and the issue has already been fixed.

**Closed by DelnarErsike** 2018-01-05 16:50 UTC
Labels: bug: application error
