### ISSUE TITLE
Essence loss is busted

### ISSUE THREAD

**Issue by chummer5hasanerror** [chummer5a/chummer5a#1702] opened 2017-06-04 16:03 UTC
## Environment
Chummer Version: .77
Environment: WIN 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour

After checking the optional rulebox for 'essence loss only effects maximum magic rating':

* When Creating a new character(Karmagen)
Lose essence = 5.00 
Take any Awakened quality (Adept)
Receive Magic attribute =  1/1 (1) on sheet

* When loading an existing career character
Character possesses 6 starting magic at chargen (adept priority b)
Character possesses pre-existing (added at chargen) essence loss, lowering magic score from 6 to 5
Character possess 4 foci (3 from chargen AND one from career mode) all at rating 4 (total rating 16)
Initiate twice across year long game/character career.
Save character.
Load character in 5.193.7X
No changes to magic score/essence loss/ foci
magic score to display as 6/7 (5) whereas:
-6 (the integer used for karma cost via advancement) 
-7 (the result of adding the current essence score and initiation grade then rounding down to the nearest whole number) 
-(5) being the actual 'attribute' value for dice pool/'magical' calculations
e.g: 
Can have up to a maximum 5 different bound foci 
Can have up to a maximum 25(magic *5) total ratings across all bound foci 

### Actual behaviour
Create New Character (Karmagen) 
Lose essence = 5.00 or so (total 1.XX essence)
Take Adept quality (untested on other awakened)
Receive magic attribute = 0/1 (0) sheet

Existing Career Character
Character possesses pre-existing (added at chargen) essence loss, lowering magic score from 6 to 5
Character possess 4 foci (3 from chargen AND one from career mode) each at rating 4 [total 16]
Load character in 5.193.7X
Immediate pop-up 'cannot have a bound foci with rating greater than magic rating' (implying a magic 5 and rating 6 focus, which is non-existent) 
OR 
'cannot have bound foci greater than 5 times magic rating' (implying that 4*4 = 21 or more)
Immediate unbinding of all foci on character
Magic displays as 5/7 (4) which is inaccurate, AND also (potentially) displays additional issues.
its seems chummers current logic is:
Total Foci rating must = (Magic Rating-Essence loss)*5 -Essence loss
Max Bound Foci must = (Magic Rating-Essence Loss) - Essence Loss

-This error expands to all characters loaded in-program, and affects any/all loaded characters with any essence loss AND a magic score. Whatever the previous Augmented magic score was, that now becomes the Base magic score and any existing alterations are now based on the 'new' number.  If this lowers your existing magic than any previously bound foci become unbound.

### Steps to reproduce the behaviour
Use Karmagen
Make awakened char with magic attribute = 1
install enough ware that essence =1.XX
Return magic attribute to 1 without spending additional(past X awakened quality cost ) karma... oh wait, you cant, thats the problem :D

Will link character file if requested.

**Comment by OLStefan** [comment] 2017-06-04 22:19
Duplicate of #1681

**Closed** 2017-06-06 14:36 UTC
Labels: bug: application error, duplicate
