### ISSUE TITLE
Changing Priority in creation caused Resonance skills to disappear

### ISSUE THREAD

**Issue by cdelstad** [chummer5a/chummer5a#1936] opened 2017-10-04 03:52 UTC
NOTE: After the issue occurred, I tried upgrading from the 193 version to 195 and it did not fix the issue.

### Environment
Chummer Version: 5a.193
Environment: Windows 10
Runtime:  .NET 4.5.1

### Expected behaviour
From the menu, when I select Special --> Change Priority Selection, I expect my Resonance skills to still be on my character. I only changed priority of resources from D to E and clicked OK.

### Actual behaviour
After I changed Priority of Resources from D to E, and clicked OK, all the Resonance skills disappeared from my character.

### Steps to reproduce the behaviour
Special --> Change Priority Selection
Change Resources from D to E.
Select OK.

### Link to affected character file
http://www.smartmarbles.com/Shadowrun/QuickSilver.chum5

**Comment by cdelstad** [comment] 2017-10-04 04:07
I was able to get it back by changing the Magic/Technomancer dropdown, then clicking OK to close the dialog. Then going back in to the Change Priority Selection and changing it to Technomancer.

**Comment by DelnarErsike** [comment] 2017-10-15 13:50
Turns out that a separate issue I just recently fixed was also the cause of this issue. I'm closing this issue for now, but if you encounter it again in a Nightly version after 2017 Oct. 16th 00:00 UTC or in a Stable version 5.196 or later, please let us know.

**Closed by DelnarErsike** 2017-10-15 13:50 UTC
Labels: bug: application error
