### ISSUE TITLE
Life Modules - Qualities removing additional karma

### ISSUE THREAD

**Issue by keidrolis** [chummer5a/chummer5a#731] opened 2016-03-01 01:14 UTC
### Expected behaviour

When a life module is added for chargen, negative qualities should not add karma and positive qualities should not subtract karma. From the book: "Note that there is no Karma bonus when taking a Region/Demographic with a negative quality, or Karma cost when taking a region with a positive quality or with bonuses to skills or attributes. All these costs and bonuses are already calculated into the Karma cost of the module. When a Karma cost or bonus is listed with a quality, it is there to denote the level of that particular quality, not the cost the character must pay." - page 66, Run Faster
### Actual behaviour

Negative Qualities gained from Life Modules add to the available karma pool for chargen, and Positive Qualities remove karma from the pool.
### Steps to reproduce the behaviour

Add any life module that includes qualities.

**Comment by SpellBinder-883** [comment] 2017-02-07 04:05
Noticed this as well when I started messing around with the lifestyle modules, and I noticed that the qualities being added were somehow being added for zero karma, so there's no karmic balance in the points.  As a quick test in Create Mode I tried an override that removed all of the tags for the positive/negative quality points to the modules, and things work now.  I have no idea how this'll translate into Career Mode, yet.

**Comment by OLStefan** [comment] 2017-10-28 21:36
Duplicate of #1276.

**Comment by OLStefan** [comment] 2017-10-30 23:04
Part of #2000.

**Closed by OLStefan** 2017-10-30 23:04 UTC
Labels: bug: application error, duplicate, life modules
