### ISSUE TITLE
Doubled value for improved ability

### ISSUE THREAD

**Issue by DonDjovanni** [chummer5a/chummer5a#3703] opened 2019-06-12 17:19 UTC
**Describe the bug**
I'm getting twice the value from improved ability for ratings over 1 and it displays twice on the skill tooltip

**To Reproduce**
Simply give a character more than one rating in improved ability

**Expected behavior**
To add it's rating once

**Screenshots**
![c5bug1](https://user-images.githubusercontent.com/51758116/59371838-5e402500-8d46-11e9-96fb-bcf914459f5f.PNG)
![c5bug2](https://user-images.githubusercontent.com/51758116/59371852-64360600-8d46-11e9-8fca-16c40c13d791.PNG)

**Character File**
[magomagò.zip](https://github.com/chummer5a/chummer5a/files/3282470/magomago.zip)

**Desktop (please complete the following information):**
Windows 10

**Comment by DonDjovanni** [comment] 2019-06-12 17:35
The character is made with Chummer 5.205.104, it manifests also with 5.205

**Comment by DelnarErsike** [comment] 2019-07-08 12:39
Whatever caused it, the issue is fixed if you change the skill's rating, and adding or removing the Improved Ability adept power does not reproduce the issue. I'm closing this issue for now, though please re-open it if you are able to reproduce it reliably and can write down the reproduction steps.

**Closed by DelnarErsike** 2019-07-08 12:39 UTC
