### ISSUE TITLE
Feature request: add multiple items from single gear screen

### ISSUE THREAD

**Issue by Cosmotronic** [chummer5a/chummer5a#2841] opened 2018-07-02 19:23 UTC
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.201.0
Environment: Win10pro
Runtime: .net.4.5.1

### Expected behaviour
ctrl or shift click to select multiple items from a list while in the "add gear" window

### Actual behaviour
single item can be selected at a time only

### Steps to reproduce the behaviour
(Enter text here)

### Link to affected character file
(Enter text here)

The current behavior is functional for most items, however adding the ability to ctrl-click or shift-click multiple items from a single category will greatly help in speeding up gearing up a character 
example of use:
Decker character is setting up a new deck, and has budgeted for buying one of each hacking program. to do so in chummer takes 90+ clicks currently.  As proposed would only take 4 clicks.

**Comment by chummer5a** [comment] 2018-07-03 07:17
Difficult to implement due to the various cost amendment things. Generally I'd suggest you make a PACK for a given set of software if it's something you're doing a lot.

**Comment by chummer5a** [comment] 2020-01-09 03:21
Duplicate of #2566

**Closed by chummer5a** 2020-01-09 03:21 UTC
Labels: feature
