### ISSUE TITLE
Refund Expense for new Skill does not remove skill

### ISSUE THREAD

**Issue by Maxis010** [chummer5a/chummer5a#1028] opened 2016-07-30 23:17 UTC
### Environment
Chummer Version: 5.182.0
Environment: Windows 10 Pro
Runtime: .NET 4.5.1

### Expected behavior
When refunding a purchase the purchase is removed and the karma restored

### Actual behavior
Karma is restored but the new skill is kept

### Steps to reproduce the behavior
Buy skill with Karma in career mode
Go to Karma and Nuyen
Undo expense on skill purchase

**Comment by chummer5a** [comment] 2016-07-31 12:09
Duplicate of #988

**Closed by chummer5a** 2016-07-31 12:10 UTC
