### ISSUE TITLE
PACKS don't save Cyberware/Bioware grade.

### ISSUE THREAD

**Issue by Skarablood** [chummer5a/chummer5a#238] opened 2015-06-17 19:16 UTC
![chummer_packs](https://cloud.githubusercontent.com/assets/7235739/8216325/24347e1a-1536-11e5-9ba0-f5d006b7e468.png)
As the title says, creating a kit does not safe the grade of ware used in it. E.g. creating a "Soldier" kit with only Alphaware  does not work correctly.

**Comment by joha4270** [comment] 2015-06-17 20:49
Can you upload a copy of your packs.xml?

Pastebin is prefered but everything i don't have to sign up for works

**Comment by Skarablood** [comment] 2015-06-18 20:04
packs.xml: http://pastebin.com/fEn5NMuS

custom_packs.xml: http://pastebin.com/nSNMEUA8

**Comment by joha4270** [comment] 2015-06-18 21:24
Think i have identified the cause. Seems to be chummer getting the ToString() instead of .Grade at frmCreateCyberwareSuite.cs:117

My branch is a of half finished changes so i won't be able to confirm my fix this week

**Comment by chummer5a** [comment] 2015-06-21 06:47
Fixed in 5.168. Wasn't using Grade.Name.

**Closed by chummer5a** 2015-06-21 06:47 UTC
Labels: bug
