### ISSUE TITLE
Weapons over availability limit are shown

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2063] opened 2017-11-18 19:49 UTC
### Environment
Chummer Version: 5.195.74
Environment: Windows 7 home edition
Runtime: (probably .NET 4.7.1)

### Expected behaviour
Do not see weapons with an availability higher than 12.

### Actual behaviour
Weapons are shown.
![sniper rifles](https://user-images.githubusercontent.com/17562417/32984186-7ecaa81e-cc99-11e7-84df-98ae6715ec33.png)

### Steps to reproduce the behaviour
Add a weapon to a character.

**Comment by DelnarErsike** [comment] 2017-11-18 19:52
Cannot reproduce. Does the character have the Restricted Gear quality, perchance?

**Comment by Lochabar** [comment] 2017-11-18 20:29
No. Here is the character file.
[Character.zip](https://github.com/chummer5a/chummer5a/files/1484999/Character.zip)

**Comment by DelnarErsike** [comment] 2017-11-19 01:27
That character is in career mode, so that checkbox shouldn't even be displayed because it wouldn't apply. I'm closing this issue, but I'll also be updating the selection windows to not even display that checkbox if the character is in career mode.

**Closed by DelnarErsike** 2017-11-19 01:27 UTC
Labels: bug: application error
