### ISSUE TITLE
'Karma cost for increasing Special Attributes is not reduced by Essence Loss' option not saving as checked

### ISSUE THREAD

**Issue by ChopperSniper** [chummer5a/chummer5a#1862] opened 2017-08-15 00:41 UTC
### Environment
Chummer Version: 5.193.207, 5.193.199, 5.193.149
Environment: (Windows 7
Runtime:  .NET 4.5.1

### Expected behaviour
On operation reload, should have that checkbox saved and karmagen file karma costs working properly.

### Actual behaviour
Option does not save, karma costs do not change.

### Steps to reproduce the behaviour
Just try saving the option and follow direction, it won't save the option.

### Link to affected character file
Any karmagen character file, no specific one.

**Comment by chummer5a** [comment] 2017-08-15 00:42
That rule doesn't currently do anything, sorry. I'll look into re-implementing it.

**Comment by drakir75** [comment] 2017-08-15 11:47
Same (or very similar) as #1808

**Comment by chummer5a** [comment] 2017-08-15 14:13
Duplicate of #1808

**Closed by chummer5a** 2017-08-15 14:13 UTC
