### ISSUE TITLE
Shapeshifters not available for chargen?

### ISSUE THREAD

**Issue by Reshy** [chummer5a/chummer5a#1551] opened 2017-03-27 18:49 UTC
Hello, I noticed that character generation seems to lack Shapeshifters as a choice of metasapient to play.  Is there any chance that they can be added into chummer?

**Comment by chummer5a** [comment] 2017-03-27 22:32
Duplicate of #826; I can't implement shifters until I sort out how to manage increasing their karma costs. The method I initially tried didn't properly update skill info and I haven't had time to come back to it.

**Closed by chummer5a** 2017-03-27 22:32 UTC
