### ISSUE TITLE
Nesting Locations

### ISSUE THREAD

**Issue by chummer5hasanerror** [chummer5a/chummer5a#3315] opened 2018-12-31 16:59 UTC
Reminder regarding #502 'Nesting Locations' and expression of ongoing desire to see feature #502 implemented.

Requested ability-
To make Location: My Jacket
Then add in a new Location: Left Pocket
and have Location: Left Pocket exist and be populated/adjustable inside the Location: My Jacket.

This gives the more OCD of us the ability to clearly indicate what possessions are in what physical location, while also giving the ability to manage a larger inventory with less effort on the players part.

**Comment by chummer5a** [comment] 2019-01-01 11:18
Duplicate of #502. Raising multiple issues for the same thing doesn't really help me get them done any sooner.

**Closed by chummer5a** 2019-01-01 11:18 UTC
