### ISSUE TITLE
AI only available in Karmagen

### ISSUE THREAD

**Issue by NorsemanJosh** [chummer5a/chummer5a#1237] opened 2016-11-24 07:39 UTC
### Environment
Chummer Version: 187.46
Environment: Win 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
AI should be available for creation in Sum to Ten and Priority.

### Actual behaviour
It is only available in Karmagen

**Comment by chummer5a** [comment] 2016-11-24 11:24
Duplicate of #891.

**Closed by chummer5a** 2016-11-24 11:24 UTC
