### ISSUE TITLE
Chummer takes a very long time when exporting a Character to JSON

### ISSUE THREAD

**Issue by bderenorcaine** [chummer5a/chummer5a#4272] opened 2020-12-09 21:44 UTC
**Describe the bug**
Since 5.213.0 chummer hangs when i try to export a character to JSON. The window that's supposed to show the JSON pops up, but takes minutes to fill. While this happens, the app stops responding. I have observed this behavior with a few very different characters.

**To Reproduce**
1. Save the Character as Created
2. Click on "File->Export"
3. See it hang for a few minutes

**Expected behavior**
I expected JSON to be produced quickly, like for most of the characters for which it still works.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.213.0

**Context**
I think the commonality in these cases is that the players these characters belonged to have added fairly sizeable mugshots, making the chummer files over a meg, sometimes over 2 megs. If chummer tries to encode the picture somehow, maybe that could be an explanation? I would expect binary data like that to be skipped.

**Comment by DelnarErsike** [comment] 2020-12-11 01:10
The hang when exporting to JSON is caused by the text box loading in the JSON information, as far as I can tell. It's a WinForms thing, the same thing that causes characters themselves to take a while to load in after you open them.

**Comment by MathisLeclair** [comment] 2021-01-16 01:31
I had the same issue,
for me the problem came from the mugshot being stored into the JSON causing it to take a long time or crash.
A temp fix for me was to remove the mugshot before exporting to JSON

**Comment by DelnarErsike** [comment] 2021-01-31 23:09
Issue has been fixed in the Nightlies by catching and removing the mugshot Base64 strings from the preview window. It seems like the actual export isn't an issue, just the mugshot info appearing in the preview window. Please re-open this if you still have an issue with exporting in the latest Nightly.

**Closed by DelnarErsike** 2021-01-31 23:09 UTC
Labels: bug: application error
