### ISSUE TITLE
Option to "Delete" a group contact does not show

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2264] opened 2018-01-06 03:28 UTC
### Environment
Chummer Version: 5.196.34
Environment: Windows 7 Home Premium (64-bit)
Runtime: (probably .NET 4.7.1)

### Expected behaviour
Option to "Delete" a contact shows for a Group contact.

### Actual behaviour
I doesn't. The group indicator seems to make the text to long to display "Delete".
![contacts](https://user-images.githubusercontent.com/17562417/34636058-4d9b05d6-f291-11e7-8512-c4dcf040e06d.png)

**Comment by DelnarErsike** [comment] 2018-01-06 21:12
Working as intended. The delete button is not visible on that contact because it is marked as "Read only", as it is part of the Prime Datahaven Membership quality. You can only delete it by removing the quality that grants you it.

**Closed by DelnarErsike** 2018-01-06 21:12 UTC
