### ISSUE TITLE
Unable to add a weapon to a Custom <Weapon type> in cyberlimbs

### ISSUE THREAD

**Issue by binnsr** [chummer5a/chummer5a#4667] opened 2022-01-10 15:56 UTC
When adding a Custom Weapon to a cyberlimb (CF 90), one should be able to specify the weapon from the appropriate subgroup.

Currently, you have to buy the 'Custom Submachine Gun' ( for example ), and then go to the Gear/Weapons tab, purchase a SubMachine Gun and then purchase the 'cyberimplanted' modification for that weapon.

Ideally, the Custom Weapon mod on a cyberlimb should be treated like a vehicular weapon mount - with the right click option for 'Weapons' submenu and 'Add Weapon', etc. on that menu.

**Comment by DelnarErsike** [comment] 2022-01-11 00:56
Duplicate of #727.

**Closed by DelnarErsike** 2022-01-11 00:56 UTC
