### ISSUE TITLE
 Issue: - program will now launch on any of my computer gives same error 

### ISSUE THREAD

**Issue by Pommanthebrit** [chummer5a/chummer5a#1371] opened 2017-01-27 09:01 UTC
### Environment
Crash ID: 3b82073e-c78d-438c-9c09-ebd7a135b676
Chummer Version: 5.190.16
Environment: Windows 10 Home
Runtime: 4.0.30319.42000

### Expected behaviour
(Should launch)

### Actual behaviour
(crash)

### Steps to reproduce the behaviour
(extract and try and use)
[i use TREND MICRO MaximumSecurity i have tryed placeing it on the exception list still crashes]

**Comment by Pommanthebrit** [comment] 2017-01-27 09:02
also the crash handler will not export the crash

**Comment by chummer5a** [comment] 2017-01-27 11:15
What error message do you get?

**Comment by Pommanthebrit** [comment] 2017-01-27 11:39
System.ArgumentException:invalid JSON primituve: .
at
System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
at
System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(int 32 depth)
at
System.Web.Script.Serializtion.JavaScriptObjectDeserializer.BasicDeserializer(String input, Int32 depthLimit,JavaScriptSerializer serializer)
at
System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input,  Type type, Int32 depthLimit)
at
System.Web.Script.Serialization.JavaScriptSerializer.Deserialize[T](Strung input)
at
CrashHandler.CrashDumper.ExtractUrl(String input) in 
C:\projects\chummer5a\Crashandler\crashDumper.cs:line 314
at CrashHandler.CrashDumper.Upload(Byte[] payload) in
C:\projects\chummer5a\Crashhandler\CrashDumper.cs:line 301
at CrashGabdker.CrashDumper.WorkerEntryPoint() in
C:\projects\chummer5a\CrashHandler\CrashDumper.cs:line 133

**Comment by Pommanthebrit** [comment] 2017-01-27 11:45
also when the crash reporter loads up the details it gives me are 
" Crash followup id =e8701325-c25e-4e3f-a6e1-51e7712ba21f
Index was out of range. Must be non-negative and less than size of the collection.
paramenter name:index"

**Comment by chummer5a** [comment] 2017-01-27 12:02
Most likely missing DLLs; do you have a Newtonsoft.Json.dll file in your Chummer folder? If not, please download the latest release from get.chummer.net and extract it manually into your folder.

**Comment by Pommanthebrit** [comment] 2017-01-27 12:10
yes i do have the Newtonsoft.Json.dll file in the folder

**Comment by chummer5a** [comment] 2017-01-27 14:07
Well, crap. I was so hopeful that that would work. Unfortunately this is a bit of a new one, so I'm not sure what the problem could be. When it crashes, you should see a blue link; can you click on that link and paste the contents of the exception.txt file?

**Comment by Pommanthebrit** [comment] 2017-01-27 14:08
i can try give me a sec

**Comment by Pommanthebrit** [comment] 2017-01-27 14:09
[exception.txt](https://github.com/chummer5a/chummer5a/files/735400/exception.txt)

**Comment by chummer5a** [comment] 2017-01-27 14:14
Aha, found it. Okay, so the problem is with one of your characters that doesn't have a proper mugshot stored in the file. As an interim you could open your registry and navigate to HKEY_CURRENT_USER\Software\Chummer5 and delete all the keys that start with MRU. I'll fix up the mugshot code, should be fixed in the next build (1-2 hours).

**Comment by Pommanthebrit** [comment] 2017-01-27 14:17
oh ok cool i put that mug shot in there like 1-3 months ago ty for the fast work just a question what tiped you off to it 
(im learning to code)

**Comment by chummer5a** [comment] 2017-01-27 14:28
At this point, it's just familiarity with what the code is doing combined with an understanding of what the error means. The exception.txt file gives the line references that show the last few actions it did. With that, I can see that it failed at line 137 of the Character Roster form, which is smack bang in the middle of the mugshot loader. From there it's just a matter of figuring out what the actual exception means (In this case it seems like the indexed position of your main mugshot is invalid) and then coding around that behaviour.

**Comment by Pommanthebrit** [comment] 2017-01-27 14:31
hmm cool so if im right your saying it way cus the program was not reading where i kept the mugshot right and then i was failing to load it without a mug shot?

**Comment by chummer5a** [comment] 2017-01-27 14:36
Kind of, yes. So basically the way we load the mugshots is to read them all into an array, then select the main image from that array based on an index, which is also saved into the file. There's no logic to prevent the index from falling out of bounds, so if you have two mugshots and the index is set to 3, there's no mugshot for it to read so it triggers the exception you hit into.

**Closed** 2017-01-27 14:36 UTC

**Comment by Pommanthebrit** [comment] 2017-01-27 14:43
confirmed fixed on my end
