### ISSUE TITLE
v5.179.760 Nightly, Metahuman Human, Metavariant Ghoul, NullReferenceException

### ISSUE THREAD

**Issue by jurgendl** [chummer5a/chummer5a#755] opened 2016-03-07 19:07 UTC
### Chummer Version

Chummer.Nightly.v5.179.760

### Expected behaviour

unknown

### Actual behaviour

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.frmPriorityMetatype.cboMetavariant_SelectedIndexChanged(Object sender, EventArgs e) in C:\projects\chummer5a\Chummer\Character Creation\frmPriorityMetatype.cs:line 772
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Chummer5
    Assembly Version: 5.179.760.0
    Win32 Version: 5.179.760
    CodeBase: file:///D:/backup/RPG/RPG%20-%20Shadowrun%20SR5/chummer/Chummer.Nightly.v5.179.760/Chummer5.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

### Steps to reproduce the behaviour

New Character, Sum to 10, Standard, Select Human and Ghoul in Combobox

##Helpful Fields
These may not be relevant in most cases. If they are, please fill them out. Otherwise, feel free to remove them.

### Operating System

Win 7 Home

### Use of international language content

none

### Last known good version

unknown

### Link to affected character file

-

**Comment by SquadronROE** [comment] 2016-05-29 01:06
This can be replicated in the latest build. Note that you need to enable all of the books in settings to allow for the Ghoul option to be selected.

**Comment by SquadronROE** [comment] 2016-05-29 17:46
This crash is ultimately caused by incomplete data in the priorities.xml file. Unfortunately, I don't have the books necessary to determine what the Value and Karma should be for all of the metavariants, but it should be as simple as just filling out those combinations (a lot of metavariant types are missing).

For now, I'm going to add in a way to catch the Null Reference exception and display an error message rather than crashing.

**Comment by SquadronROE** [comment] 2016-05-29 17:57
Issue temporarily resolved with a change to frmPriorityMetatype.cs, adding error handling.

**Closed** 2016-06-19 11:04 UTC
Labels: bug: application error
