### ISSUE TITLE
Advanced Lifestyles

### ISSUE THREAD

**Issue by HaikenEdge** [chummer5a/chummer5a#446] opened 2015-10-12 11:45 UTC
As it stands, Advanced Lifestyle options always cost money, but according to the books, and clarified in *Hard Targets*, outing and services do not have to have their Nuyen price paid if the minimum lifestyle is equal to or greater than that of the minimum lifestyle of the outing or service, unless the user is also out of lifestyle points.

**Comment by chummer5a** [comment] 2015-10-12 12:00
Yeah, the intended behaviour is that if your lifestyle is in the allowed
categories it should be free. I'll need to review that section of code.

**Comment by chummer5a** [comment] 2015-10-16 11:23
Ha, obvious problem was obvious. Fixed in 5.176.

**Closed by chummer5a** 2015-10-16 11:23 UTC
