### ISSUE TITLE
GMC Armadillo missing std equipment.

### ISSUE THREAD

**Issue by bulldogc** [chummer5a/chummer5a#4751] opened 2022-03-23 00:40 UTC
**Describe the bug**
The GMC Armadillo should come with more standard equipment, some of it might not have real entries and some might be tricky to implement, but should atleast come with off-road suspension and tires.

**To Reproduce**
Add GMC armadillo in any character. Stock gear currently included is off-road suspension

**Expected behavior**
Would expect to see off-road suspension,  off-road tires(mentioned in description as having both). Based on the description and the stat table, there should probably be some option to include a free drone rack, workshop, smugglers compartment, or rigger cocoon somehow? This part might be trickier.

**Comment by binnsr** [comment] 2022-03-23 13:00
My thoughts -- is this a dupe of #4670?

For now, I've been buying off road tires for free on my vehicles and using the 'Special Equipment' to add the pods.. 
I.e. 'Special Equipment (Riggers Cocoon)'

Could add Model-specific mod entries for the vehicle to cover the interchangeable boxes, although R5 doesn't include pricing for the boxes, so I guess, putting it at 0 and leaving it to the GM's discretion..

**Comment by bulldogc** [comment] 2022-03-23 13:23
Def a dupe of that from the looks. I do think regardless of the special bed items the tire should be included as stocks items with a working "install" check box so that people can still take them off.
I like the idea of the model specific bits. From the description it sort of sounds like it should come with all of them and the owner has the option of installing one of them at a time. So maybe making them free model plugins and only allow one of them, similar to a weapon mod slot or something. The real question is are they suppose to take up and body mod slots or not.

**Comment by binnsr** [comment] 2022-03-23 13:30
The books don't say, but ShadowHaven Reloaded treats it this way:
![image](https://user-images.githubusercontent.com/26882158/159710229-c35b4188-fc71-4ec4-96c9-b6d33c58882d.png)
The text says 'you name it, the back of the Armadillo *can* have a bed for it' so I'd lean towards the way SHR does it.. 
As far as them taking up body slots, I wouldn't have them using slots as the pod is part of the base vehicle, regardless of which pod is mounted.

**Comment by Teksura** [comment] 2022-08-18 05:29
One potential solution could be to just make the default behavior add modifications you can buy and install, since RAW gives no cost or stats for them, could just have it give a prompt asking how much the pod costs. 


Although for some of these, a good argument can be made on some of their costs already because they appear elsewhere in the book. This is a more viable source than an arbitrary number number Shadow Haven made up a few years ago. The Workshop costs 5000¥. Drone Racks have different costs based on their size and type. A Rigger Cocoon is 1500¥. The rest, well, your guess is as good as mine.

**Closed** 2022-08-23 06:41 UTC
Labels: bug: XML, wontfix
