### ISSUE TITLE
Credstick Crash

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#1983] opened 2017-10-22 10:29 UTC
### Environment
Chummer Version: 5.195.149
Environment: Windows 10
Runtime:  probably .NET 4.5.1

### Expected behaviour
Chummer not to crash :-)

### Actual behaviour
When adding a credstick of any kind to a character in create mode, chummer crashes. (Haven't tested career mode)

### Steps to reproduce the behaviour
Create any character. Add a credstick.

### Thanks
For all the work getting Chummer5A steadily better and better.

**Comment by DelnarErsike** [comment] 2017-10-22 11:52
Unable to reproduce. Adding credsticks to new characters works fine for me, as does adding credsticks to previously saved characters, both in create and career modes.

**Comment by Zitchas** [comment] 2017-10-22 17:13
I can confirm this crash, although I am using 5.195.48.

I tried adding a gold credstick to a new character, and it worked just fine. But when I tried to add a platnium, silver, or standard credstick to the character after having already added a gold one, it crashed.

In subsequent testing, I have found that adding any of platnium, silver, or standard credstick as the first piece of gear on a new character results in a crash.

I was able to add the Certified Credstick (2050), Fake Credstick (2050), and Standard Credstick (2050) successfully without a crash (all together at the same time), but  it then crashed when I added a Certified Credstick (Gold)

I will update to .49 and attempt see how things go.

**Comment by Zitchas** [comment] 2017-10-22 17:20
Updated to 5.195.59
With all sourcebooks enabled.

I can add all (2050) credsticks without a problem. All other credsticks cause a crash immediately when I add them (referring to gold, silver, and platnium credsticks)

I tried turning off all sources (except for the core book), and tried each of the gold, silver, platnium, and standard credsticks, and I still go a crash each time.

**Comment by OLStefan** [comment] 2017-10-22 17:27
I can reproduce the error, seems to be a problem with the CultureInfo. Which in this case is responsible with interpreting points and commas in numbers (decimal point or decimal comma).

**Comment by Zitchas** [comment] 2017-10-22 17:30
I just re-installed Chummer from the 5.195.49 nightly download, and tried again.

With all sourcebooks off except for the core rulebook, created a brand new character, and then tried to add each of the four credsticks. It crashed every time. (tested with standard, gold, silver, and platnium)

**Comment by OLStefan** [comment] 2017-10-22 17:42
Found the problem, should be fixed in Version 5.195.50.

**Closed** 2017-10-22 17:42 UTC
Labels: bug: application error
