### ISSUE TITLE
Extra Fragile Critter power points to page 191RF when it should point to page 191 howling shadows

### ISSUE THREAD

**Issue by Tyler111762** [chummer5a/chummer5a#4419] opened 2021-05-06 21:14 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Character File**
If applicable, add your character file to help explain your problem. Character files can be compressed into zips and uploaded here, or have their extension renamed to .txt.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 5.201.22]

**Additional context**

**Comment by DelnarErsike** [comment] 2021-05-06 21:44
Duplicate of #4420.

**Closed by DelnarErsike** 2021-05-06 21:44 UTC
Labels: bug: data file content, good first issue
