### ISSUE TITLE
Wired reflexes 3 + reaction enhancer 3 wireless

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#2864] opened 2018-07-12 21:40 UTC
### Environment
Chummer Version: 5.201.0
Environment: Windows 10
Runtime: probably .NET 4.5.1

### Expected behaviour
When in career mode being able to get +6 to Reaction with
WR+RE wireless on. 
Ideally just a toggle for wireless on or off, but improvements work ok.

### Actual behaviour
Possible to get up to +4. Not +6.

### Steps to reproduce the behaviour
(Enter text here)

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment] 2018-07-13 01:22
Strictly speaking a duplicate of #633. Not particularly difficult to implement with the current infrastructure, needs a PairBonus node that links to either bit of ware with a prerequisite for the other and an augmax improvement.

**Comment by chummer5a** [comment] 2019-01-26 11:54
Closed by 2491b81b

**Closed by chummer5a** 2019-01-26 11:54 UTC
Labels: bug: data file content, enhancement
