### ISSUE TITLE
Can't open character after update without crash

### ISSUE THREAD

**Issue by PADDINGTONREX** [chummer5a/chummer5a#2939] opened 2018-08-22 23:47 UTC
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: 5.202.0
Environment: WINDOWS 10
Runtime: .NET 4.5.1

### Expected behaviour
Loads character file from previous build

### Actual behaviour
Crashes upon opening character file
[chummer_crash_131794543290809220.txt](https://github.com/chummer5a/chummer5a/files/2312325/chummer_crash_131794543290809220.txt)

It doesn't seem to be all my character files, just the different versions of one I'm trying to play. 

### Steps to reproduce the behaviour
When I open a previously made/finished character file it crashes

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment] 2018-08-23 00:59
I suspect this is the adept power issue; should be fixed properly in 5.202.5+, please try with the latest nightly build.

**Comment by PADDINGTONREX** [comment] 2018-08-23 01:05
Thank you so much for getting back to me so fast! I will do just that.

**Comment by DelnarErsike** [comment] 2018-09-27 13:14
This issue has not gotten an update in about a month, so I'm closing it for now with the assumption that whatever caused the original issue has been fixed in the nightly branch. If the issue is still present however, feel free to (request to) reopen it.

**Closed by DelnarErsike** 2018-09-27 13:14 UTC
Labels: bug: application error, response pending
