### ISSUE TITLE
Crash on program opening

### ISSUE THREAD

**Issue by jeoc42** [chummer5a/chummer5a#1471] opened 2017-02-24 18:36 UTC
### Environment
Crash ID: bffd504a-6891-4efa-a915-79bb73ad4842
Chummer Version: 5.190.116
Environment: Windows 7 Home Premium
Runtime: 4.0.30319.42000

### Expected behaviour

Program launches when executable is opened.

### Actual behaviour

Program crashes immediately with a "process not running" error.

### Steps to reproduce the behaviour

Attempt to launch program on my system.

**Comment by chummer5a** [comment] 2017-02-25 02:07
I don't have access to the crash dumps at the moment, does the crash handler load? If yes, you should see a blue link on that window; if you can click that and paste the contents of the exception.txt file, I'll be able to figure out what's going on.

**Comment by reiichitanaka** [comment] 2017-02-25 12:51
Same issue, and I have no crash handler loading. I'm on Windows 7 Ultimate (64 bit).

**Comment by chummer5a** [comment] 2017-02-25 14:14
Hrm. Can you try updating your .Net version to 4.6.2? Chummer's supposed to be targeted against 4.5.2, but someone else mentioned that that fixed it for them. https://www.microsoft.com/en-au/download/details.aspx?id=53344

**Comment by joha4270** [comment] 2017-02-27 09:12
This might be a duplicate of #1484, which was fixed in https://github.com/chummer5a/chummer5a/releases/tag/Nightly-v5.191.27

**Closed** 2017-03-06 03:46 UTC
