### ISSUE TITLE
Can't raise MAG with Karma at chargen on burnout characters with more than 3 essence loss

### ISSUE THREAD

**Issue by ivancraddock** [chummer5a/chummer5a#2288] opened 2018-01-11 07:01 UTC
### Environment
Chummer Version: 5.169.40
Environment: Windows 10
Runtime: Unknown

### Expected behaviour
When an awakened character loses essence at chargen, it should have two effects: 1.) Maximum MAG is reduced according to the essence loss and 2.) Current MAG rating is reduced according to the essence loss. At this point, it should be possible to raise magic using either Karma or Special Attribute points.

### Actual behaviour
When essence is reduced by 3.01 to 4 points, it's impossible to raise MAG above zero. This includes using either Karma or Special Attribute points. Also, reducing essence by 2.01 to 3 points creates an effect where raising MAG by 2 points only yields a MAG of 1.

Please see this screenshot: https://imgur.com/a/RIgk7

### Steps to reproduce the behaviour
Create an awakened (adept) character, and burn out some of their essence. Burn out their essence by 3.01 to 4 points. Try to buy their MAG back up using either Karma or Special Attribute Points. 

### Link to affected character file
https://drive.google.com/open?id=1tzv02veFVXkOlWW04LemrsKgTKKzqeep

**Comment by DelnarErsike** [comment] 2018-01-11 07:32
The attribute should be increasable with Karma, yes, and that's been fixed in the latest commit. However, I am not sure if you are allowed to increase with special attribute points after burning out due to the order in which the chargen process is performed (similar to how you cannot spend skill points to buy specializations for skills for which the first rating was bought with karma).

HeroLab is also no help on this matter, as its burnout method works in a way that is definitely not RAW (e.g. it does not let you buy up to MAG 1 with karma if you have lost 1 more MAG to essence loss than what your priority would have granted you).

**Comment by drakir75** [comment] 2018-01-11 19:32
There is no ambiguity to spending special attribute points on Magic (IMO). Karma has to be spent after special points. Special points should only be able to raise Magic to 6 (or whatever max Magic is). As chummer is at the moment (version 196.40) Special points does not work properly. (Even if you raise Magic to 6 before you burn out by buying cyberware.)

Steps to reproduce: Get a human adept (Magic prio D, Meta prio C). Raise magic to 6. Buy augmentations for between 3 and 4 essence. Your Magic should be 2. It is for some reason 0.

**Comment by DelnarErsike** [comment] 2018-01-11 20:00
That issue with priority points should also be fixed in the next nightly.

The ambiguity for special attribute points is there the same way there's ambiguity around being able to spend skill points to buy specializations for skills in which only karma was used to buy ratings. There are also many accepted cases that would definitely violate the order in which priority chargen steps are resolved; e.g. you can buy qualities with skill prerequisites, e.g. Loss of Confidence, at step 4, even though the skill ratings needed to fill their prerequisites can only be bought at step 5 (skill point spending) and step 7 (spending leftover karma). The orange stamp is staying.

**Comment by reyjinn** [comment] 2018-03-03 10:08
Decided to comment here rather than open a new issue since it seems to me that what I've encountered is related to this.

If you burn out magic "past" 0 at chargen, you cannot use special atts to raise magic unless you spend enough to counter weigh the essence loss past your starting magic score. This is as it should be AFAIK.

However, if you use karma to buy up magic, 5 karma will immediately give you 1 Magic. In this case you don't even lose your special attribute, so you could use it to raise edge. This cannot be how it is intended to work, it would be bonkers.

**Closed** 2020-04-27 14:28 UTC
Labels: bug: application error, errata/clarification required
