### ISSUE TITLE
Unable to add Weapon Mount to Drone in Create Mode: Auto-Generated Issue from Crash: ID b6481a02-c637-4feb-97d1-0dff2011229b

### ISSUE THREAD

**Issue by PirateSwayze** [chummer5a/chummer5a#4684] opened 2022-02-01 00:19 UTC
### Environment
Crash ID: b6481a02-c637-4feb-97d1-0dff2011229b
Chummer Version: 5.220.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000
Option upload logs set: OnlyMetric
Installation ID: 272c85bc-d8be-409d-b7cc-8e3957036443

### Expected behaviour
Add Weapon Mount to Drone

### Actual behaviour
Chummer crashes

### Steps to reproduce the behaviour
Character in Create Mode
Add MCT-Nissan Roto-drone
Add Weapon Mount

### Crash Description
Object reference not set to an instance of an object.
   at Chummer.CreateWeaponMount.RefreshComboBoxes() in C:\projects\chummer\Chummer\Forms\Creation Forms\CreateWeaponMount.cs:line 938
   at Chummer.CreateWeaponMount.frmCreateWeaponMount_Load(Object sender, EventArgs e) in C:\projects\chummer\Chummer\Forms\Creation Forms\CreateWeaponMount.cs:line 136
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message

**Comment by DelnarErsike** [comment] 2022-02-01 02:46
Duplicate of #4682

**Closed by DelnarErsike** 2022-02-01 02:46 UTC
