### ISSUE TITLE
[Bug] Unable to add Cyberware or Bioware

### ISSUE THREAD

**Issue by DelinquentPanda** [chummer5a/chummer5a#2163] opened 2017-12-12 04:25 UTC
While accessing the add cyberware or bioware tabs the catagory and grade dropdown boxes are empty and no 'ware is listed This occurs in both create and career modes (seems to work fine in v196.0)

### Environment
Chummer Version: Nightly-v5.196.1
Environment: Windows 7 64 bit
Runtime: .Net 4.6.1

### Expected behaviour
being able to see a list of cyber or bioware when clicking the add cyberware or add bioware button

### Actual behaviour
the drop down boxes are blank and the list of available ware is empty

### Steps to reproduce the behaviour
Try to add ware to any current or new character.

**Comment by DelnarErsike** [comment] 2017-12-12 04:55
I'm unable to reproduce the issue with the latest dev build, but I suspect the problem may have been fixed in a hotfix. If you can, see if you are able to reproduce this with Nightly-v5.196.3 or later.

**Comment by Zitchas** [comment] 2017-12-12 14:13
I just tried to replicate this with v5.196.2 and Chummer crashed when I clicked the "add cyberware" button on the "Cyberware and Bioware" tab. Is this likely related, or should I create a new issue?

**Comment by DelinquentPanda** [comment] 2017-12-13 02:38
with 196.3 seems to have fixed everything though thanks!

**Closed** 2017-12-13 02:40 UTC
Labels: bug: application error, response pending
