### ISSUE TITLE
Adding Thundercloud Morgan crashes my install

### ISSUE THREAD

**Issue by oxford-fumble** [chummer5a/chummer5a#2187] opened 2017-12-15 18:43 UTC
### Environment
Chummer Version: 5.196
Environment: Win10 (native), Win7 (on Mac, though Wine)
Runtime: 471 / 461 on Wine

### Expected behaviour
- On the "Vehicles and Drones" tab, click on "Add Vehicle"
- Select "Thundercloud Morgan"
- Vehicle gets added to list under "Selected Vehicles"

### Actual behaviour
- On the "Vehicles and Drones" tab, click on "Add Vehicle"
- Select "Thundercloud Morgan"
- Chummer crashes

### Additional information
- This occurs in Create and Career Mode
- My install on Mac is less stable (and so, problems also occur with other cars), but crashes also occur on my PC (Win10, .NET 4.7.1), only for the Thundercloud Morgan - as far as I can see
- I tracked down the problem change to Chummer 5.195.84 - ie. 83 works fine, 84 crashes.

### Link to affected character file
No character file - this was happening on new characters, so if you can't reproduce, it's probably a problem with my setup (I do experience the issue on PC as well, though...).
I enclose screen shots that show 83 works, 84 crashes.
<img width="1181" alt="screen shot 2017-12-15 at 18 16 06" src="https://user-images.githubusercontent.com/4921171/34055590-ca6bdf70-e1c7-11e7-86cf-2c7d2c2a638c.png">
<img width="1181" alt="screen shot 2017-12-15 at 18 17 04" src="https://user-images.githubusercontent.com/4921171/34055591-ca8284aa-e1c7-11e7-97bf-b5255b363316.png">
<img width="1180" alt="screen shot 2017-12-15 at 18 18 22" src="https://user-images.githubusercontent.com/4921171/34055592-ca988c5a-e1c7-11e7-81cb-cb2966700ce9.png">

**Comment by oxford-fumble** [comment] 2017-12-15 18:53
Just for completeness's sake: screenshots from Chummer 5.196.5 crashing on my PC.

![chummer down](https://user-images.githubusercontent.com/4921171/34055931-282932ba-e1c9-11e7-8932-0a9eda0b82bb.png)
![chummer down 2](https://user-images.githubusercontent.com/4921171/34055930-280dcc96-e1c9-11e7-9ced-bc8530048812.png)

**Comment by DelnarErsike** [comment] 2017-12-15 18:59
I appreciate the thorough reporting, but the problem was already reported earlier today in #2183 and fixed shortly thereafter. The cause was that the "Fixed" mount in its data file was mistyped as "Fixes". The fix will be in the next nightly, but if you don't feel like updating and/or waiting for the nightly, you can fix the issue yourself by going into `data\vehicles.xml` and fixing the typo in the Thundercloud Morgan entry.

**Closed by DelnarErsike** 2017-12-15 18:59 UTC
Labels: bug: application error

**Comment by oxford-fumble** [comment] 2017-12-15 19:42
Ok thanks!
One day, I will make a valid contribution ;)
