### ISSUE TITLE
Changing language in Options crashes CrashHandler then Chummer

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#2076] opened 2017-11-20 19:08 UTC
### Environment
CChummer Version: 5.195.76
Environment: Windows 7 home edition
Runtime: (probably .NET 4.7.1)

### Expected behaviour
Be able to change language in options

### Actual behaviour
Change language, don't even get to the save the change, and CrashHandler crashes, followed by chummer.

### Steps to reproduce the behaviour
Start chummer. Select options. Change language to German.

### Link to affected character file
CrashHandler crash:
![crashhandler 1](https://user-images.githubusercontent.com/17562417/33036278-ce40e402-ce25-11e7-9d78-4c23b490629b.png)
![crashhandler 2](https://user-images.githubusercontent.com/17562417/33036279-ce86c8b4-ce25-11e7-824f-a800a50a3fbf.png)
![crashhandler 3](https://user-images.githubusercontent.com/17562417/33036280-ceacf07a-ce25-11e7-8be9-82c05d502691.png)

Then chummer:
![chummer crash](https://user-images.githubusercontent.com/17562417/33036297-db699728-ce25-11e7-88d1-cf18e9aa45eb.png)

There is no CrashHandler dump file.

**Comment by DelnarErsike** [comment] 2017-12-07 14:59
Have you encountered this issue since you reported it originally? I was never able to replicate it.

If you have not encountered the issue since, then I will close this issue.

**Comment by Lochabar** [comment] 2017-12-07 15:10
Still happening in 5.195.98. Just change the language in Options and crash handler crashes, doesn't even reach the point of being asked if I want to save the change. Don't know if it relevant but the default character sheet goes blank just as the crash handler crashes.

**Comment by DelnarErsike** [comment] 2017-12-07 15:31
Does this also occur if you change languages in the character sheet viewer?

**Comment by Lochabar** [comment] 2017-12-07 18:36
I don't currently have the ability to change language in the viewer (I have in the past)
![viewer](https://user-images.githubusercontent.com/17562417/33732211-911d42ae-db7d-11e7-8b02-a83a4e1769de.png)

**Comment by DelnarErsike** [comment] 2017-12-08 00:11
Could you try a clean reinstall? From what I can tell, the issue is that you have languages set up that do not have sheets associated with them.

**Comment by Lochabar** [comment] 2017-12-08 01:02
I clean install every release.
I have created an en-GB language setup to allow me to test "foreign" language character sheets. What seems to be missing that is causing the problems?
Where is the sheets association made?

**Comment by DelnarErsike** [comment] 2017-12-08 01:08
Relevant entry in the (new) wiki: [Correcting Translations/Localizations](https://github.com/chummer5a/chummer5a/wiki/Contributing-to-Chummer5a#correcting-translationslocalizations)

I pushed a commit to the dev branch (will show up in the next nightly, not 5.195.99 though) that will prevent those crashes from occurring with languages that have no sheets tied to them, but you will still need to tie in those sheets if you actually want to print in your custom languages.

**Comment by Lochabar** [comment] 2017-12-08 01:12
The instructions seems to be for modifying the "Chummer5a's Visual Studio project file and make sure they are copied when the Chummer5a project is built". But I'm not building the project. So there must be a file that performs the association; I will need to adjust this file if you can tell me what it is.

**Comment by DelnarErsike** [comment] 2017-12-08 01:14
Quoting by verbatim. First and third paragraphs tell you exactly where that association is:

> Localizations in Chummer5a are split into two components: translations for the program itself and translations for character sheets.

> Translations for the program itself are controlled by .xml files within [repository]\Chummer\lang. Changing the data there follows similar rules as adding or correcting base data content. However, you may also use a tool included in the Chummer5a download called Translator.exe as another way to modify translations for the main program.

> Translations for the character sheets are split between .xsl/.xslt files located in [repository]\Chummer\sheets\[language] and the [repository]\Chummer\data\sheets.xml file. The former controls localized content within the character sheets themselves, while the latter dictates the character sheet names and filenames that show up within the main Chummer5a program. Modifying the former follows the same rules as correcting character sheets, while modifying the latter follows the same rules as adding or correcting base data content.

**Comment by Lochabar** [comment] 2017-12-08 15:56
I created a custom_sheets data file for en-gb and the crash no longer occurs and I am now able to change languages in the character sheet viewer.

**Closed** 2017-12-09 04:15 UTC
Labels: bug: application error, enhancement
