### ISSUE TITLE
Karma Creation unfunctional

### ISSUE THREAD

**Issue by chummer5hasanerror** [chummer5a/chummer5a#1691] opened 2017-06-01 17:29 UTC
### Environment
Chummer Version: 193.71
Environment: WIN 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Karma character creation system to account for attributes
If i up an attribute, this will deduct karma from the creation total (default 800) and also be tracked in the sidebar under Karma Summary

### Actual behaviour
No changes in UI to indicate deductions to creation total, or karma summary sidebar

### Steps to reproduce the behaviour
Make new character, selecting karma as build system

### Link to affected character file
Will upload if needed

**Comment by OLStefan** [comment] 2017-06-01 18:29
Duplicate of #1675 (Which seems to not be resolved)

**Closed** 2017-06-02 02:42 UTC
Labels: bug: application error, duplicate
