### ISSUE TITLE
SURGE counting against Positive Quality Karma Limit

### ISSUE THREAD

**Issue by HaikenEdge** [chummer5a/chummer5a#426] opened 2015-10-01 21:59 UTC
SURGE isn't a positive quality to begin with, yet it's being counted against a character's Positive Karma limit. Should probably get that fixed.

**Comment by chummer5a** [comment] 2015-10-02 02:13
Nah, the changeling qualities don't count for the quality limit. They're
just counted against positive qualities on the karma summary. I guess I
could throw in a Special Qualities label that includes things like Adept as
well?

**Comment by HaikenEdge** [comment] 2015-10-02 03:12
Yet, when I have a character with Changeling (Class III SURGE), Biocompatibility and Human-Looking, it counts for 41 Karma of Positive Qualities, and it prevents me from putting the character into career mode, even though Biocompatibility and Human-Looking together is only 11 Karma worth of Positive Qualities.

**Comment by chummer5a** [comment] 2015-10-02 03:26
Works fine for me; could you upload your character file somewhere?

**Comment by HaikenEdge** [comment] 2015-10-02 03:29
http://www.mediafire.com/download/nzi9x3er9bc7bpa/Mercy+%28Playing%29.chum5

**Comment by HaikenEdge** [comment] 2015-10-02 15:00
In Career mode, all the Changling SURGE levels cost double Karma (so Class I SURGE costs 20, Class II SURGE costs 30, and Class III SURGE costs 60). Probably another unintended side-effect of the Changeling (Class X SURGE) being treated as qualities.

**Comment by chummer5a** [comment] 2015-10-05 04:53
Hrm. There's something odd going on here; removing and re-adding the quality made it work fine. Career mode makes sense, but there is the question of whether it's even possible to make a changeling after creation.

**Comment by Mastaziel** [comment] 2015-10-06 08:26
Hi, I'm having the same issue. I have taken SURGE3 off and re added it and other qualities. But it wont let me go to "Created" mode as it says I have more than 25 points in positive qualities.

https://www.dropbox.com/s/ykn26i30fgbxl08/Satyr.chum5?dl=0

Awesome program though, very well set up.
Thanks
Clayton

**Comment by chummer5a** [comment] 2015-10-06 08:59
Haa. Found the problem there. I didn't think to check for if any of the metavariants could start with a metagenetic quality. Fixed in the next build.

**Comment by Mastaziel** [comment] 2015-10-06 22:03
Awesome. If only all systems had this kinda thing. Really impressive.

Thanks chummer
Clayton

**Comment by chummer5a** [comment] 2015-11-09 09:27
Fixed as of 5.176, probably earlier.

**Comment by HaikenEdge** [comment] 2015-11-09 14:26
Fixed, but not quite. It seems now you're limited to having as much karma in SURGE qualities as the type of SURGE quality you picked, which, as far as I can tell, isn't how the rules work.

**Comment by chummer5a** [comment] 2015-11-10 03:52
I'm sure there's a reason I thought that Changeling Class II only got 15 karma points worth of metagenetic qualities. Will be fixed in 5.177.

**Comment by HaikenEdge** [comment] 2015-11-23 03:16
SURGE is once against counting against the Positive Quality Karma limit, even though the limitation on the number of SURGE qualities you may have remain corrected.

**Comment by nemthe** [comment] 2016-02-22 20:52
So I have seemingly the same error in version 5.178, where it should be fixed right?
Positive Qualities:
-Changeling SURGE III
-Functional Prehensile Tail
-Monkey Paws
-Nasty Vibe
-Thermographic Vision
Negative:
-Berserker
-Critter Spook
-Mood Hair
-Poor Self Control (Combat Monster)
-Signature
-Striking Skin Pigmentation

SURGE Karma would be 22 to 22, 20 Karma in negative Qualities, and 30 for the SURGE (which as I understand, shouldn't count towards positive qualities)...

Character Sheet Here:
http://www.mediafire.com/view/d69vtcmi68aja6z/Baboon_Backup.chum5

If the error is something on my side then i don't see it..

**Comment by HaikenEdge** [comment] 2016-02-22 20:54
It was fixed briefly between November 9th and 22nd, at which point it was broken again.

**Comment by chummer5a** [comment] 2016-02-22 22:39
Can't reproduce as of Nightly-v5.179.715
<https://github.com/chummer5a/chummer5a/releases/tag/Nightly-v5.179.715>.

**Comment by HaikenEdge** [comment] 2016-02-22 22:47
Can confirmed it's resolved in the Nightly build. I generally don't run nightly builds, so wasn't sure up until then.

**Comment by nemthe** [comment] 2016-02-22 22:59
yup, in the nightly it works again xD but then I wonder why it wasn't in the Stable 178 version but in the current nightly... kinda weird xD but i guess that explains that at least

**Comment by chummer5a** [comment] 2016-02-22 23:04
Well the nightlies are a fair way ahead of the last release candidate at this point. Anyhoo, issue closed.

**Closed by chummer5a** 2016-02-22 23:04 UTC
Labels: bug, errata/clarification required
