### ISSUE TITLE
school of hard knocks / college education / technical school not working

### ISSUE THREAD

**Issue by Rootlord** [chummer5a/chummer5a#408] opened 2015-09-22 16:16 UTC
Hello!

I tried to get one of these qualitys to work, but they don't. 
Maybe I understand them wrong? They should give you 2 points on specific knowledge skills, if you invest 1, right? (with your free knowledge points at character generation)
I have not tested if the cost reduction post - creation and post rating 3 is working.

**Comment by cfresquet** [comment] 2015-09-22 18:29
I can confirm this isn't implemented correctly in the code (I noticed this while fixing Jack of all Trades), but I forgot to enter the issue for tracking.

I can take a look at this today, I was just looking at this last week, so I'm up to speed on it.

**Comment by chummer5a** [comment] 2015-09-23 11:24
Hrm. The karma's working properly, but the point increase isn't. Odd.

**Comment by cfresquet** [comment] 2015-09-23 19:29
Ok, putting in a pull request for my fix for this.

I wound up rewriting more of the point cost calculation code than I was expecting to clean things up and make it easier to work on -- so any additional eyes taking a look and testing what I did would be appreciated.

**Comment by joha4270** [comment] 2015-09-23 19:35
Still not seeing that pull \:P

**Comment by cfresquet** [comment] 2015-09-23 19:39
Ug. Turns out I'll need to hand-merge with the changes from "Partial fix for Uneducated karma costs" that went in a few hours ago -- :dancer: 

Plus being employed means I have to go to some meetings in a bit, so it may be a few hours yet before I can put the pull request in.

**Comment by joha4270** [comment] 2015-09-23 19:41
Its fine, i was just mashing F5 to see it as it came in.

**Comment by cfresquet** [comment] 2015-09-23 20:15
Ok, NOW it has been submitted. :)

Reading through the group skills code while I was doing the merge, I don't think it is doing combination points+karma calculations right, but that's a bug for a later fix.

**Comment by chummer5a** [comment] 2015-11-09 08:35
Fixed as of 5.176, assuming nothing else has broken in interesting ways.

**Closed by chummer5a** 2015-11-09 08:35 UTC
