### ISSUE TITLE
Damage Compensators don't work properly

### ISSUE THREAD

**Issue by Sturmkind** [chummer5a/chummer5a#1231] opened 2016-11-20 09:54 UTC
### Environment
Chummer Version: 5.187.34
Environment: Win 8.1
Runtime: .NET 4.5.1

### Expected behaviour
- ~~Thickened Digestive Tract Lining reduces Lifestyle costs by 10%~~
- ~~Infected: Mutaqua turns mages into Mystic Adepts and "Normals" into Adepts~~
- ~~Selecting any other Taser after selecting the Defiance EX-Shocker shows their stats~~
- High Pain Tolerance (Quality) and Damage Compensators "stack" (in the example of both being rating 3 the first negative modifier would be at the 9th damage track field)
- ~~Bilateral Coordination Coprocessor automatically adds the Ambidextrous quality~~
- ~~Ambidextrous quality can be added once and then doesn't appear on the selectable qualities anymore (like every other quality)~~
- ~~Metasapients (Pixies, Nagas, Centaurs, ...) can't take the Technomancer quality (since their inherent magic shouldn't be able to mix with resonance)~~
- ~~Pixies can Ascense (since they have Astral Perception and a magic attribute naturally) without taking a magic quality (Adept/Mage/...)~~

### Actual behaviour
- ~~Thickened Digestive Tract Lining increases Lifestyle costs by 10%~~
- ~~Infected: Mutaqua gives Mages Powerpoints (but doesn't change the quality?) and leaves "Normals" normal and without magic (but this can be handled by giving them the Adept quality for free, so maybe this point is moot)~~
- ~~Chummer crashes upon first clicking on the Defiance EX-Shocker (without adding it to gear) and then clicking on another taser (maybe wait a few seconds when replicating the bug) while still displaying the stats of the EX-Shocker until it crashes~~
- High Pain Tolerance (Quality) overrides Damage Compensators (in the example of both being rating 3 the first negative modifier is at the 6th damage track field)
- ~~Bilateral Coordination Coprocessor doesn't automatically add the Ambidextrous quality~~
- ~~Ambidextrous can be added multiple times and still appears as selectable quality~~
- ~~Metasapients can take the Technomancer quality (and it does some funny stuff to their Initiation/Submersion Tab -> called initiation, selection to add stuff to grades is called metamagic and contains echoes...) -> p. 142 in Run Faster "Infection and Resonance" mentions the incompatability of Magic and Resonance~~
- ~~Pixies can't take any magic-active skills at all without the appropriate qualities~~

### Minor Issues/Suggestions/Ideas
Weapons: 
- ~~Cearmic/Plasteel Components should be incompatible with several other accessories (i.e. Smartlinks, Chameleon Coatings, ...), so maybe have them exclude each other?~~
- ~~Concealed Holsters can only be used with Tasers or Pistols (Holdout - Machine Pistols?)~~
- ~~Easy Breakdown requires a "side" slot~~
- ~~Ammo Skip can only be applied to weapons with cylinder/drum magazines, but then to all of those who do (so maybe add a underbarrel slot for weapons like the Ruger Super Warhawk?)~~

Cyberware
- ~~(Very niche) Adding a cyberlimb to a pixie and then adding any strength related modifications crashes chummer (I guess because even the standard Strenght of 3 is above the natural maximum for pixies)~~

Skills
- ~~Selectable specializations for "Small Unit Tactics" Knowledge Skill seems to be the same as for the "Running" Active Skill (intended?)~~

Sorry for the dump of things on this one, but I didn't want to create a ton of singular issues (should I do so in the future so you can address them one by one?)
Hope this helps improve the program
And as always, awesome work, guys (and girls?)

**Comment by chummer5a** [comment] 2016-11-20 12:33
Right, so. First off, as a general rule, individual issues are easier for me to keep track of, since I can work on a single issue and push a commit that resolves it. Saves having to go through and mark off particular items, or work on everything at once.

As far as the issues that I haven't strikethrough'd go:
* The Infected thing is a bit complex; because of the way we treat qualities and improvements it's difficult to replace a quality and provide for the ability to fall back. The current behaviour should be unlocking all of the adept abilities though, is it not working properly?
* Tasers should also be fixed in the current nightlies, there was an issue with the underbarrel melee contact weapon that caused the crash.
* Damage compensators are currently not working as intended, and are part of #821. The current behaviour is a terrible workaround.  
* Ambidextrous is unlimited for the sake of Nartaki and such; tricky to implement a single-limb restriction as is, so it's sort of a workaround.

Weapons generally have a lot of tedious weird restrictions that aren't spelled out very well, so the traditional approach has to be leaving it up to the user to decide what they can and cannot take. We recently added the ability to require/forbid stuff though, so it should be mostly doable. 

* Ceramic components is infuriating and vague. Realistically I would need to see a list of everything it doesn't stack with, but the smartlink and chameleon coating should definitely be in there. Will be fixed in a later patch. 
* Ammo skip will need some work

Pixielimb will be... interesting, but might be an easy fix.

**Comment by Sturmkind** [comment] 2016-11-20 16:03
Then sorry for the inconvenience of making a dump issue pool. I'll remember to make single issues from now on ;)

As for the remaining issues:
- Infected: The only "not properly functioning" I found was when an infection granted awakene powers to non-awakened characters (Mutaqua, Nosferatu, ...), but that can be circumvented by simply adding the appropriate quality "for free"
- I tried to recreate the Taser issue and narrowed it down to the Tiffani-Defiance Protector (which, for me, causes a crash in the latest nightly upon selection)
- Damage Compensators: sorry, I didn't know about that issue and even though I normally try to read back to not cause duplicates that was a little too far ;) (I usually read the first page, but as there are only 3 a quick search will be made in the future ^^)
- Ambidextrous: okay, that seems fair. I hadn't thought of those SURGE/Nartaki characters (Now that you mention it I remember reading something about needing it for every additional hand or so)
- Weapons: Yeah, I can understand that. Aside from things in slots that are already excluded pretty well with the current builds this can be tough. The current way of doing it is okay (though it can be tedious to look through all the books to see if all the mods I like fit. Not a problem of Chummer though ;))
- Pixielimb: I'm not even sure if those should even be considered now that I think about it ^^ I mean... what do they use, Barbie limbs?

All in all I would consider this issue closed if you could maybe take a look at the Tiffani-Defiance Protector and fix that crash (if it is not something exclusive to me...)

**Comment by DelnarErsike** [comment] 2016-11-20 16:16
Fixed the Tiffani-Defiance Protector crash, it was due to another oversight on my part (like the Defiance-EX Shocker thing) when I renamed Gecko Grip. Also, you'll be happy to hear that I've been working on a subsystem for Chummer with which I am able to do the exact weapon accessory filters you mentioned, e.g. filtering Speed Loader to only show up for Revolves and filtering Concealable Holster to only show up for weapons with a base concealability of 0 or less (pistol-sized). Both are included in my next pull request, as are mutual exclusion tags for things like Ceramic/Plasteel Components and the five types of Advanced Safety System.

As for Ammo Skip, that's based on HT needing errata, just like how Electronic Firing is a barrel mod instead of an internal one.

**Closed** 2017-10-03 00:29 UTC
Labels: bug: application error
