### ISSUE TITLE
Mouse Wheel usage is dangerous

### ISSUE THREAD

**Issue by tomservaux** [chummer5a/chummer5a#1297] opened 2016-12-14 20:44 UTC
I have had many problems with my group (who are all new to Chummer and Shadowrun) where they will have negative karma or invalid stats because they accidentally rolled the mousewheel thinking they were scrolling when they had a field selected. I think it might be a good idea to disable mousewheel support on any controls involving selecting a numerical value, maybe even on the drop downs for specialization too because sometimes just hovering over those and scrolling will select a value.

**Comment by chummer5a** [comment] 2016-12-15 03:35
Duplicate of #1217. 

Generally speaking I'm not super interested in removing that behaviour, as it's a standard Windows action for hovering over a control to activate it. Still, should be possible to hide it behind an optional rule and redirect the mousewheel event to the parent control without too much hassle.

**Comment by tomservaux** [comment] 2016-12-15 12:32
If it were me I would add a guard to the stats and skills that defaulted to off. A small toggle button (maybe with a pin icon) would work. Once the user is happy with their stats or skill levels they can lock them all by clicking this button. This could be for all stats or you could have a toggle next to each stat that the user clicks when they are happy with that stat. The individual stat approach is kind of heavy but this app needs a lot of controls anyway so I don't think that would deter me from having them for each stat.

**Comment by joha4270** [comment] 2016-12-15 12:51
I'm very strongly against a pin button as the solution.

First of all, i don't think we can make what it does obvious. I'm willing
to bet money on us getting bug reports on skills/stats not working because
somebody activated it without knowing what it does or on accident.
Second, I don't want that interaction model at all. You have a safety cover
on the button that launches a missile, not over the steering wheel. And in
my experience, skills/stats are changed around often during the creation
process. Lot closer to the steering wheel than the launch.
Third, Where do you stop? Once we add it for skills, why not add it for
cyberware grades. Or spirit services. Or power point ratings. There are
plenty of places where one could be included. Where do we draw the
arbitrary line and say no more? We could put it everywhere, but there are
way bigger issues that could be solved a lot faster.
Fourth, what is the actual gain? In the end, we move a fat finger issue
from the mouse wheel somewhere on the screen to a left click somewhere on
the screen. Not a huge benefit and quite a lot harder to fix if you don't
already know the solution.

**Comment by chummer5a** [comment] 2017-05-28 02:08
Fully implemented in the latest commit.

**Closed by chummer5a** 2017-05-28 02:08 UTC
Labels: bug: application error, enhancement
