### ISSUE TITLE
Unable to hide German sourcebooks with amend rules

### ISSUE THREAD

**Issue by Lochabar** [chummer5a/chummer5a#3130] opened 2018-10-20 00:20 UTC
**Describe the bug**
Trying to hide the German books from Sourcebooks list. I created an "amend_books" by copying /customdata/SR Missions 1.4 Rules/amend_books and modified it to contain only the German books.

**To Reproduce**
1. Go to /customdata/
2. Unzip attached zip file
3. Start Chummer
4. Options->Option Rules->check "XT - Exclude German sourcebooks"
5. Save changes, restart, Options
6. See error

**Expected behavior**
None of the German exclusive books are listed under Options.

**Screenshots**
This is the top of the "amend_books" file
![amend](https://user-images.githubusercontent.com/17562417/47248811-b353b300-d3d2-11e8-82b7-87f1d0972972.png)

![rules](https://user-images.githubusercontent.com/17562417/47248817-c49cbf80-d3d2-11e8-991d-f79e2876bb61.png)

![sourcebooks](https://user-images.githubusercontent.com/17562417/47248819-cd8d9100-d3d2-11e8-9a2a-5c1afd03f904.png)

[XT - Exclude German sourcebooks.zip](https://github.com/chummer5a/chummer5a/files/2497663/XT.-.Exclude.German.sourcebooks.zip)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Version: 5.201.71 [and prior]

**Additional context**
This used to work, although I don't remember how many versions back.
Has something changed with the Optional Rules processing? or the use of amend/custom files in general?

**Comment by chummer5a** [comment] 2018-10-20 07:48
You're probably looking at the globaloption view. It's kind of working as intended that the full list of books is available there in order to map PDFs and such; the list of books under Character Options uses the hide filters as you'd expect.

**Comment by Lochabar** [comment] 2018-10-20 12:55
I opened an existing character that was created with the Missions rules options selected and the German sourcebooks are listed AND also the non-mission legal books such as Bullets & Bandages.

**Comment by DelnarErsike** [comment] 2018-10-20 14:16
Do those books appear in the Character Options tab, where you can select which sourcebooks to enable and disable, or only in the Global Options tab, where you control which sourcebook is tied to which PDF file and with what page offset?

Notice the difference between the two: the first controls character-specific options, i.e. options that theoretically could change from character to character (e.g. how many limbs to use, to how many decimal places should Essence be tracked), while the second controls options that are character-independent and global to Chummer5a (e.g. whether to use Linux printing code or not, whether or not to automatically check for updates on startup, etc.).

**Comment by Lochabar** [comment] 2018-10-20 14:38
Both. The images I sent are from the Global Options with no character loaded. When I have a character loaded and use options the same problem is present.

**Comment by DelnarErsike** [comment] 2018-10-20 14:54
You misunderstand. The Global Options list has nothing to do with enabling sourcebook content for characters and is purely for setting/changing PDF options.

See, your amend file works:

![options_work](https://user-images.githubusercontent.com/727731/47256917-844b4900-d487-11e8-9c8e-fde7085d1e6a.png)

Note the tab I have selected and note how books you have disabled (like Schattenhandbuch) don't appear in the list books I can enable for the character. Also notice how the list in Character Options is titled "Sourcebooks to Use" for enabling and disabling sourcebook content, whereas the list in Global Options is titled "Edit Sourcebook Info" for editing the PDF info associated with some sourcebook.

I'm closing this issue because features are working as intended: the German sourcebooks still show up in the list of sourcebooks for editing PDF infos, but don't show up and are force-disabled in the list of sourcebooks to enable for a given character.

**Closed by DelnarErsike** 2018-10-20 14:54 UTC
