### ISSUE TITLE
Chummer5 sluggish on attribute change (no, it's not Windows Defender)

### ISSUE THREAD

**Issue by EnslavedMuse** [chummer5a/chummer5a#5094] opened 2023-12-29 05:00 UTC
It sounds just like the Windows Defender issues- but I've created exceptions, inbound and outbound rules, I've disabled WD, disabled anti-virus, run as administrator, updated, uninstalled, reinstalled, run in compatibility with every possible windows version selection.... and it still goes through an incredible "loading" period each time anything is done, and after a handful of attempts the program becomes unresponsive.

Pretty much begging here.... what else can I do?

**Comment by JoschiZ** [comment] 2023-12-29 18:16
What version are you on exactly? The recent nightlies all faced that issue.
The newest one may be better, but not sure right now.

**Comment by DelnarErsike** [comment] 2024-01-03 17:02
Duplicate of #5080, closing this issue

**Closed by DelnarErsike** 2024-01-03 17:02 UTC
